danieljprice/phantom

build/Makefile, src/main/energies.F90, src/main/evwrite.F90, src/main/phantom.F90, src/main/utils_indtimesteps.F90, src/setup/setup_star.f90, src/tests/test_nonidealmhd.F90, src/utils/analysis_MWpdf.f90, src/utils/analysis_clumpfind.F90
Will now print correct particle numbers to log files when using MPI
=> MPI bug fixes

src/setup/setup_shock.F90, src/setup/setup_sphereinbox.f90, src/tests/testsuite.F90
As discussed, I have added the values relevant to the .in file and dumpfile into the .setup files for sphereinbox and shock.
In the testsuite, I have also reset iverbose between every test since that value is changed within a few specific tests.
=> added values to .setup as per issue #51

src/main/checksetup.F90, src/main/force.F90
=> (forces) fix artificial conductivity for non-ideal EoSs

.gitattributes, data/cooling/cooltable.dat, data/forcing/forcing.dat, data/isolatedgalaxy/magalie_lowrestest/m.dat, data/velfield/cube_v1.dat, data/velfield/cube_v2.dat, data/velfield/cube_v3.dat, docs/clusters.rst, docs/gitinfo.rst, docs/monarch.rst, docs/nci.rst, docs/ozstar.rst, docs/running-mac.rst, src/main/part.F90, src/tests/test_part.f90
=> (#42) remove files using git-lfs

src/main/eos.F90, src/main/eos_mesa.f90, src/utils/analysis_common_envelope.F90
=> Add mesa temp

src/setup/setup_star.f90
Modified the star_setup so that when using the MESA EoS and reading i…n a stellar profile file the internal energy is calculated from density and pressure using the MESA EoS rather than copying the one in the profile. This yields more consistent stellar setups.
=> Modified the star_setup when using the MESA EoS

src/main/checksetup.F90, src/main/eos.F90, src/main/force.F90, src/setup/density_profiles.f90
Changes requested by @danieljprice
=> Fix art con

src/setup/setup_star.f90
Now when setting up a star using the MESA EoS the code asks for mean molecular weight, hydrogen mass fraction and metals mass fraction.
=> Added additional setup variables for the MESA EoS

src/main/cooling.F90, src/main/initial.F90, src/main/readwrite_dumps_fortran.F90
fixes cooling complier warnings and readwrite build failure
=> compiler warnings & build failure fixes

src/main/eos.F90, src/setup/set_fixedentropycore.f90, src/setup/set_softened_core.f90, src/setup/setup_star.f90
Partially addresses issue #91 and does some cleaning up (see commit messages).
Miguel: Please test if you can set up a MESA EoS star with this.
=> Star cleanup

.mailmap
Update my (Daniel Mentiplay's) email address in `.mailmap`.
=> Update email address in mailmap

src/setup/set_disc.F90, src/setup/setup_dustsettle.f90
Discs around both binaries were not properly set and both ended up around the primary.
COM adjustment has to be included
=> (bugfix) disc setup around binaries

build/Makefile, src/main/checkoptions.F90, src/main/force.F90, src/main/initial.F90, src/main/step_leapfrog.F90, src/main/utils_summary.F90, src/setup/setup_sphereinbox.f90, src/tests/test_sedov.F90
These commits include several, small changes that clean up aspects of the code.
=> general cleanup

src/main/cooling.F90, src/main/eos.F90, src/main/initial.F90, src/main/step_leapfrog.F90, src/main/writeheader.F90, src/setup/setup_unifdis.f90
The temperature floor is now a variable in the .in file rather than hard-coded.  All temperature floor related variables initialisations are  in cooling.F90 rather than eos.F90.
I have also made a single init_cooling, rather than having several subroutines depending on h2chemistry.
=> Thermal floor (now in cooling rather than eos)

src/main/step_leapfrog.F90
=> Enable particle waking for MPI

build/Makefile, src/utils/analysis_mcfost.f90
mcfost-phanton interface needed to be fixed to take into account recent changes
=> (mcfost) Fixing interface

docs/getting-started.rst, src/main/dens.F90, src/main/ptmass.F90, src/main/step_leapfrog.F90, src/setup/density_profiles.f90
The Bonnor-Ebert sphere calculation has been made more robust when selecting physical mass and physical radius.
This request includes a few minor clean-ups as well.
=> BE sphere update + minor changes

src/setup/density_profiles.f90, src/setup/setup_star.f90
=> read logRho from MESA profile

scripts/writemake.sh
Type of PR: 
Bug fix (makefile)
Description:
Fixes #255 -- Wrapper makefile does not propagate exit code of inner makefile
Testing:
GitHub workflows
=> ensure makefile exit codes are propagated through

AUTHORS, src/main/cons2primsolver.f90, src/main/evolve.F90, src/main/initial.F90, src/main/readwrite_dumps_fortran.F90
Type of PR: 
Description:
There are still some print statements and warnings that are executed by all MPI tasks, instead of just master. This PR addresses some of these.
Testing:
GitHub CICD workflow, but this PR only affects code output to the terminal/log
=> Reduce mpi output

build/Makefile_qscripts
Type of PR: 
other
Description:
fix the makefiles qscript target to write correct slurm script for MPI jobs
=> fix slurm MPI qscript

AUTHORS, src/main/eos.F90
Type of PR: 
Description:
Addresses (partially) the excess output issue (#272)
Testing:
Confirm that qfacdisc is not printed repeatedly
=> only print qfacdisc on master

src/main/ionization.f90
Type of PR: 
Enhancement
Description:
Fix accuracy of rapid tanh evaluation
Testing:
Ran EOS test.
No
=> (eos-gasradrec) fix accuracy of rapid tanh evaluation

src/setup/setup_disc.f90
Type of PR: 
change to prompts/.setup file when adding planets to a disc setup
Description:
No longer asks "Do you want to add planets?" followed by number of  planets. Just asks for the number of planets,  which can be zero
Testing:
Rerunning ./phantomsetup with selected options, works with both interactive and non-interactive setup
=> (setup_disc) simplify prompting/.setup by only asking for nplanets

src/main/cons2prim.f90, src/main/deriv.F90, src/main/evolve.F90, src/main/evwrite.F90, src/main/externalforces.F90, src/main/timestep.F90, src/main/utils_indtimesteps.F90, src/main/utils_timing.f90
Type of PR: 
modification to existing code 
Description:
-bug fix for updating non-ideal MHD coefficients
-patch for stability when increasing dtmax automatically
-trivial formatting changes
Testing:
modifications were made during testing of low-res sims
=> Minor updates

docs/ozstar.rst
Type of PR: 
documentation
Description:
added how to request 32 core node on sstar queue
Testing:
n/a
Did you run the bots? n/a
=> added information about sstar queue job submission on ozstar

src/utils/moddump_rotate.f90
Type of PR: 
modification to existing code 
Description:
Add printing statement to tell user what angular velocity is being added to the dump
Testing:
Have used the moddump with the printing statement
No
=> add print statement to moddump_rotate

.github/workflows/benchmarks.yml
Type of PR: 
Bug fix
Description:
YAML syntax error was not detected until PR was merged into master
Testing:
None
=> fix syntax error in #319

src/main/mpi_derivs.F90
Type of PR: 
Description:
`cell%owner` can be used to infer the cell message direction. There is no need to determine the direction prior to sending the message and use the MPI tag. This frees up the MPI tag to be used for other purposes.
Testing:
`make MPI=yes test` on local machine.
Did you run the bots? via pre-commit
=> use cell%owner to determine message direction

.github/workflows/benchmarks.yml, .github/workflows/build.yml, src/main/utils_datafiles.f90
See #335 #275 #339
Type of PR: 
Bug fix
Description:
Use the -k flag for curl when downloading datafiles to get around the certificate issue
Testing:
As per #339 :
```
export PHANTOM_DIR=~/phantom
make SETUP=test phantomtest && ./bin/phantomtest eos
```
=> (datafiles) bug fix; use -Ok flags for curl downloads of data files

src/main/eos_gasradrec.f90, src/utils/moddump_recalcuT.f90
Type of PR: 
Description:
take smaller multiplicative guesses in temperature solving for robustness
Testing:
Used in https://ui.adsabs.harvard.edu/abs/2022MNRAS.516.4669L/abstract
no
=> (eos-gasradrec) increase robustness of temperature solving

src/main/options.f90, src/main/readwrite_infile.F90, src/utils/analysis_mcfost.f90
Type of PR: 
Bug fix 
Description:
Change the name of "mcfost_uses_PdV_and_shockheating"
Testing:
Compiled on my laptop
=> Shortened "mcfost_uses_PdV_and_" to "mcfost_uses_PdV"

src/main/cooling_gammie.f90, src/setup/setup_disc.f90
Type of PR: 
Bug fix /
Description:
fixing bug: beta cooling in input file not showing up
Testing:
we check that the input file is written correctly 
=> fixing cooling option missing in .in file

build/Makefile_setups
Updated Makefile_setups with 2 new setups to simulate an isothermal self-gravitating disc (with dust) and with disc viscosity.
Name of the setups:
- isosgdisc
- dustyisosgdisc
=> new isothermal (dusty) self gravitating disc setups

docs/selfgravity_gravitationalinstability.rst
New file "selfgravity_gravitationalinstability.rst".
Documentation for simulate self-gravitating and gravitationally unstable discs (setups sgdisc, dustysgdisc, isosgdisc, dustyisosgdisc).
=> Documentation for self-gravity and gravitational instability

src/main/checksetup.F90, src/main/dust.F90, src/setup/setup_dustybox.f90
Type of PR: 
Bug fix
Description:
fixes #374
Testing:
check that SETUP=dustybox gives fatal error if setup with the old dust particle type
=> (dust) bug fix, closes #374

docs/examples.rst
Added link to the example page
=> (docs) Update examples [skip ci]

.github/workflows/build.yml, Makefile, README.md, build/Makefile, scripts/buildbot.sh, scripts/dataread.py, scripts/test_analysis_ce.py, scripts/test_analysis_ce.sh, src/main/options.f90, src/main/readwrite_dumps_fortran.F90, src/utils/analysis_common_envelope.F90
Type of PR: 
addition to test suite
Description:
Unit tests for analysis_common_envelope contributed by Miguel Gonzalez-Bolivar
Testing:
the analysis_ce unit test was/can be checked as follows:
```
cd scripts
```
change listofcomponents on line 75 of buildbot.sh to just:
```
listofcomponents='analysis'
```
then run the buildbot as usual:
```
./buildbot.sh
```
this should compile and run phantomanalysis and perform the unit test for the analysis_common_envelope module, with eventual output something like:
```
Phantom analysis: may your paper be a happy one
Passed: separation_vs_time.ev created
Passed: boundunbound_vs_time.ev created
Passed: energy.ev created
Passed: No NaN values found in separation_vs_time.ev
Passed: No NaN values found in boundunbound_vs_time.ev
Passed: No NaN values …
```
=> (test_analysis) added unit tests for analysis_common_envelope to GitHub actions

.github/pull_request_template.md
Type of PR: 
Other
Description:
Pull request template now asks if relevant documentation has been updated
Testing:
Reviewed by Daniel, James and Bec
Did you run the bots? no - not needed
=> Add documentation ask to pull request template

src/setup/setup_hierarchical.f90
Type of PR: 
CHESS logo in setup_hierarchical.f90
Description:
Add a good-looking ASCII art logo in the newborn Complete Hierarchical Endless System Setup
Testing:
It compiles and characters are well aligned
=> Hierarchical systems

src/utils/moddump_rad_to_LTE.f90
Basically does `vxyzu(4,i) = vxyzu(4,i) + rad(iradxi,i)`.
=> add moddump to convert radiative to non-radiative dump, assuming LTE

build/Makefile_setups, src/main/energies.F90, src/main/utils_binary.f90, src/main/utils_datafiles.f90, src/setup/set_binary.f90, src/setup/set_star.f90, src/setup/setup_sedov.f90, src/setup/setup_solarsystem.f90, src/utils/utils_mpc.f90
Type of PR: 
new setup
Description:
Setup for solar system asteroid orbits, useful for plotting the observed distribution of asteroids in the solar system. These are placed as "km-sized" dust particles
Testing:
./phantomsetup solar
=> Solar system

src/utils/moddump_sink.f90
Type of PR: 
Description:
Testing:
=> (moddump_sink) correct displayed value of sink luminosity

src/main/radiation_implicit.f90
Merge parallel sections in implicit radiation code.
=> Omp radiation

AUTHORS, build/Makefile, build/Makefile_setups, src/main/evolve.F90, src/main/inject_BHL.f90, src/main/inject_asteroidwind.f90, src/main/inject_bondi.f90, src/main/inject_firehose.f90, src/main/inject_galcen_winds.f90, src/main/inject_keplerianshear.f90, src/main/inject_rochelobe.f90, src/main/inject_sne.f90, src/main/inject_steadydisc.f90, src/main/inject_unifwind.f90, src/main/inject_wind.F90, src/main/inject_wind.f90, src/main/part.F90, src/main/radiation_implicit.f90, src/main/wind.F90, src/setup/phantomsetup.F90, src/setup/setup_binary.f90, src/setup/setup_wind.f90, src/tests/test_sedov.F90, src/tests/test_wind.f90, src/tests/testsuite.F90, src/utils/analysis_common_envelope.f90, src/utils/analysis_dustywind.f90, src/utils/struct_part.f90, src/utils/utils_mpc.f90
Type of PR: 
new test_wind.f90 routine
Description:
Provide a test suite for non dusty  winds from a single star
Testing:
I ran make test and passed all the tests
=> Add wind tests to the test suite (non dusty winds)

build/Makefile, build/Makefile_setups, src/utils/analysis_binarydisc.f90
Type of PR: 
Bug fix
Description:
updating mcfost hdf5 settings
=> HDF5ROOT changed to HDF5_DIR

AUTHORS, src/main/checksetup.F90, src/main/cooling_gammie.f90, src/main/radiation_implicit.f90, src/main/utils_implicit.f90, src/utils/combinedustdumps.f90
same as #460 but with build failure fixed
=> same as #460

AUTHORS, src/main/checksetup.F90, src/main/cooling_gammie.f90, src/main/radiation_implicit.f90, src/main/utils_implicit.f90, src/utils/combinedustdumps.f90
Type of PR: 
Description:
Calculate the Gammie cooling from stellar origin
Testing:
Compiled phantom
=> (cooling) Calculate the Gammie cooling from stellar origin

src/utils/analysis_common_envelope.f90
- In output_divv_files, allow choosing to print "0".
- Modifications to code to print planet profile quantities.
=> (CE-analysis) minor updates

src/utils/analysis_common_envelope.f90
Type of PR: 
Description:
Testing:
=> Include Roche utils in requires_eos_opts list

src/main/units.f90
Type of PR: 
Bug fix
Description:
Fixed units.f90 bug.
Testing:
Code compiles.
Did you run the bots? No
Did you update relevant documentation in the docs directory? No
=> Fixes #498

docs/user-guide/index.rst, docs/user-guide/relaxation.rst
Type of PR: 
Documentation
Description:
Added documentation for the stellar relaxation procedure "relax-o-matic".
Testing:
The rst file has been converted to html using python module rst2html to see if it contains any errors.
Did you update relevant documentation in the docs directory? yes
=> Added documentation for stellar relaxation

build/MakeKrome, build/Makefile, build/Makefile_defaults_ifx, build/Makefile_systems
Type of PR: 
fixes #558 
Description:
Testing:
=> implement new intel ifx compiler setup

src/main/ptmass.F90, src/tests/test_ptmass.f90, src/tests/testsuite.F90
Type of PR: 
new physics 
Description:
added sink surface force from Ayliffe & Bate (2010)
Testing:
Added a unit test.
=> added sink surface force from Ayliffe & Bate (2010)

AUTHORS, docs/developer-guide/datafiles.rst, src/main/inject_randomwind.f90, src/main/metric_tools.f90, src/main/ptmass.F90, src/main/utils_gr.f90, src/setup/setup_asteroidwind.f90
Type of PR: 
new injection of anisotropic winds, as per #578
Description:
same as #578, merge conflicts fixed
Testing:
Compile and run via GitHub actions
=> merge #578

build/Makefile_setups, src/main/geometry.f90, src/main/inject_randomwind.f90, src/main/random.f90, src/main/units.f90, src/setup/setup_asteroidwind.f90
Type of PR: 
modification to existing code (asteroidwind)
Description:
Change the asteroidwind to randomwind. Update the unit calculation, now the mdot can be input with units.
Add a Gaussian random distribution position. The particles can be injected in a Gaussian distribution in theta. 
Testing:
I tested the old method 'asteroidwin', and a new 'randomwind', both can inject particles properly. 
=> an unpadte to randomwind

AUTHORS, build/MakeKrome, build/Makefile, build/Makefile_setups, docs/external-utilities/mcfost.rst, src/main/eos.f90, src/main/force.F90, src/main/inject_masstransfer.f90, src/main/part.F90, src/main/substepping.F90, src/main/units.f90, src/setup/relax_star.f90, src/setup/set_solarsystem.f90, src/setup/set_star.f90, src/setup/setup_masstransfer.f90, src/setup/setup_solarsystem.f90, src/setup/setup_sphereinbox.f90, src/tests/test_ptmass.f90, src/tests/test_units.f90, src/tests/testsuite.F90, src/tests/utils_testsuite.f90, src/utils/moddump_sink2gas.f90, src/utils/moddump_sphNG2phantom_addBfield.f90
Type of PR: 
new moddump
Description:
- new sink2gas moddump that converts sink particles into stars / balls of gas
- fix further issues in relaxation procedure for asteroids
- rename set_bodies.f90->set_solarsystem.f90
- unit tests for units module added
- bug fixes in in_units() routine to convert a quantity in code units to physical units 
```
rho_cgs = in_units(rho,'g/cm^3')
```
- issue with printing of FAILs for real valued number tests in the test suite fixed
Testing:
Added unit tests for units module, now part of testsuite
=> Relax asteroids v2

src/setup/setup_grtde.f90
Type of PR: 
Modification to existing code
Description:
In the .setup file for setting up stars with grtde, users can now choose to calculate the initial velocity of a star in General Relativity (GR) for parabolic orbits around non-spinning black holes.
- Added a boolean parameter use_gr_ic in the .setup file to enable the calculation of GR initial conditions.
- The initial velocity of the star is computed in Boyer-Lindquist coordinates in setup_grtde.f90 (see, e.g., Appendix in Tejeda et al. 2017, MNRAS, 469, 4483–4503).
- The total specific energy, calculated within GR, is used to numerically determine the initial velocity via the Gradient Descent method.
=> (grtde) Add option to compute initial velocity of a star using GR initial conditions

build/Makefile, src/main/egg.f90, src/main/evolve.F90
Description:
Made for (and by) bored procrastinators. 
- [Makefile; egg.f90; evolve.f90] Main code (src/main)
- [Add eggs] Physics improvements
Testing:
Run the eggs
Did you add comments such that the purpose of the code is understandable? yes
Is there a unit test that could be added for this feature/bug? no
=> Eggs anyone?

.github/pull_request_template.md, .github/workflows/mcfost.yml, .mailmap, build/Makefile
Description:
Check that phantom2hdf5 compiles and runs, this is done inside the mcfost workflow since we have a dump file available.
Testing:
Will be checked in p-r
Did you add comments such that the purpose of the code is understandable? yes
Is there a unit test that could be added for this feature/bug? yes
If so, please describe what a unit test might check:
added
Related issues: #161 #660
=> Phantom2hdf5 unit test
