danieljprice/phantom

src/setup/setup_shock.F90
In my previous commit (pull request #54), I added all .in file parameters that were in the choose_shock subroutine to the .setup file.  Here, I removed the parameters that are constant for all shocks, and these parameters are now defined in the main setup subroutine.  Although alphau differs between shock 10 and the rest, this value is initialised differently in options.f90 for gr=.true. which is required for shock 10.  alpha remains in the .setup since it is either 0 or 1, depending on the shock choice.  The remaining .in parameters in the .setup file vary depending on the shock.
=> (setup_shock) removed some parameters out of the .setup file

docs/fork.rst, docs/gitinfo.rst, src/main/checksetup.F90, src/main/cooling.F90, src/main/dens.F90, src/main/eos.F90, src/main/externalforces.F90, src/main/force.F90, src/main/initial.F90, src/main/part.F90, src/main/readwrite_dumps_fortran.F90, src/main/readwrite_infile.F90, src/main/step_leapfrog.F90, src/main/utils_summary.F90, src/main/writeheader.F90, src/setup/set_sphere.f90, src/setup/set_unifdis.f90
1) Cooling:
Added Koyama & Inutuska (2002); this and Gammie cooling are solved explicitly in force; the remaining cooling options are still implicitly calculated in step.  I am not confident that the implicit cooling is fully and correctly operational.  I have corrected a few bugs and added a few fail-safes.  Concern 1 is that the cooling timestep was never initialised nor calculated in step (the latter has been corrected).  Concern 2 is that the new default cooling requires a pre-processor flag and optional arguments, which is very dangerous; default cooling should not require pre-processor flags or optional arguments (so I suggest returning the default to Gammie).  
2) Initial conditions:
Added option to initialise an ellipse or an elliptical void; at the moment, we cannot initialise an …
=> updated cooling & elliptical initial conditions

src/main/part.F90, src/main/partinject.F90, src/main/readwrite_dumps_common.F90, src/main/readwrite_dumps_fortran.F90, src/main/readwrite_dumps_hdf5.F90, src/main/utils_allocate.f90, src/main/utils_dumpfiles.f90, src/main/utils_dumpfiles_hdf5.f90, src/tests/test_rwdump.F90, src/utils/moddump_binarystar.f90, src/utils/splitpart.f90, src/utils/utils_splitmerge.f90
Particle IDs are now tracked.  This is required for MPI and when particles are added/killed between dumps.  In analysis files, to always perform calculations on the same particle, use
do = 1,npart
j = iorig(i)
xi = xyzh(1,j)
...
enddo
This should solve issue #27 , although some debugging for MPI and hdf5 dumps may be required.
=> Tracking particle IDs

src/main/part.F90, src/main/partinject.F90, src/main/readwrite_dumps_common.F90, src/tests/test_rwdump.F90
We now properly track the maximum particle ID and use this as the reference point for all future IDs.  This prevents duplicating IDs when particles are deleted prior to new particles being added to the list.
=> (particle ID) bug fix to prevent reusing IDs

build/Makefile, src/main/utils_filenames.f90, src/setup/density_profiles.f90, src/setup/set_cubic_core.f90, src/setup/set_fixedentropycore.f90, src/setup/set_softened_core.f90, src/setup/set_stellar_core.f90, src/setup/setup_star.f90, src/utils/moddump_binary.f90
Cleanup of star setup, core-softening, and MESA file reading modules. Closes issue #91
- setup: Wrap up core-softening code into subroutine `set_softened_core` in the new module `setsoftenedcore`. `set_softened_core` finds the composition, finds the core mass and radius, and calls the softening routines `set_cubic_core` or `set_fixedS_softened_core` depending on the softening option. The cubic core softening module has been renamed from `setsoftenedcore` to `setcubiccore`
- setup: Variable name `hdens` has been changed to `rcore`.
- MESA reading in `rho_profile`: Subroutine `read_mesa` has been upgraded to read both P12-styled profiles and MESA profiles. `read_mesa_file` is no longer necessary.
=> Star cleanup

src/setup/set_binary.f90, src/setup/setup_disc.F90
Add subroutine set_multiple in set_binary.f90 in order to substitute a sink with a binary oriented at will.
=> Add possibility to set up an hierarchical triple system embedded in a circum-triple disc

docs/hierarchicalsystems.rst, src/setup/set_binary.f90
set_binary is now treated as a lower level routine called by set_multiple in order to build hierarchical systems.
=> Resolve the code overlap between set_binary and set_multiple

src/utils/moddump_dustadd.f90
In the file "moddump_dustaff.f90", when the 2 fluids method is selected, the code takes the dimension and the density of dust grains in physical units (cm, g/cm^3) and does not convert them in code units. I fixed this problem by converting the size and the density in code units.
Cristiano Longarini
cristiano.longarini@unimi.it
=> fix unit conversion of distance and mass in moddump dustadd.f90

src/main/initial.F90, src/main/part.F90, src/main/ptmass.F90, src/setup/set_unifdis.f90, src/setup/setup_disc.F90, src/tests/test_ptmass.F90, src/tests/test_sedov.F90
added icreate_sinks=2, where the checks for sink formation are performed on the particles within 2h of the candidate gas particle; this is what sphNG does.  This method facilitates the quicker formation of sink particles than the original/default icreate_sinks=1 which checks all particles within h_acc.
=> New sink formation criteria

build/Makefile, src/main/eos.F90, src/main/h2cooling.f90, src/main/inject_sne.f90, src/main/partinject.F90, src/main/readwrite_infile.F90, src/main/step_leapfrog.F90, src/main/utils_summary.F90, src/main/writeheader.F90, src/setup/set_Bfield.f90, src/setup/setup_unifdis.f90
I have added an option to impose a thermal floor to prevent a simulation from crashing with utherm < 0.  This is controlled by the logical use_Tfloor and the value Tfloor in eos.F90.  This should be used only as a last resort, which is why they're hardcoded and not in the .in file.  By default, the thermal floor is off.
@rieder and myself have found a few extreme simulations where this is necessary, and simply reducing the timestep does not work as a result of the predictor-corrector method.
=> Thermal Floor + added Balsara & Kim defaults

src/main/linklist_kdtree.F90, src/main/ptmass.F90, src/setup/set_shock.f90, src/setup/set_sphere.f90, src/setup/set_unifdis.f90, src/setup/stretchmap.f90, src/tests/test_ptmass.F90
Fixes #94
- Fix incorrect array size
- Use modern fortran procedure pointer
- save xyzcache in ptmass
=> Fix seg fault in test suite on sink particle creation

src/main/dtype_kdtree.F90
Fixes #144
`MPI_TYPE_STRUCT` was removed from the MPI 3.0 standard, and replaced with `MPI_TYPE_CREATE_STRUCT`, which has the same interface.
Presumably the old subroutine requires `disp` to be `kind=4`, and breaks for anything else (e.g. MPI_ADDRESS_KIND==8) . Replacing this call with `MPI_TYPE_CREATE_STRUCT` solves the problem.
Throw error when the extent is incorrect, instead of trying to recover.
=> Remove deprecated MPI_TYPE_STRUCT 

.github/workflows/benchmarks.yml
Fixed wget command arguments.
Old log files were being downloaded into the incorrect subdirectory. This caused historical benchmarks to be missing in the new log files, meaning the webpage only showed the most recent data point.
=> Fix benchmark history logging

.github/workflows/benchmarks.yml
`plot-benchmarks` only appends the latest value to stats.txt each time it is run. It does not rebuild the whole log, so stats.txt needs to be stored on the server for the full plot to be generated.
=> Save perflog (stats.txt) to web server

src/main/part.F90
alphaind is not used with DISC_VISCOSITY
=> fix mpi buffer size when DISC_VISCOSITY is enabled

src/main/utils_dumpfiles.f90
When support for `integer(kind=1)` arrays was added for native phantom files, the incorrect type for `dum` was used, causing the read offset to be set incorrectly. This results in integer arrays being read incorrectly whenever an offset was required.
The same mistake was made when c21cf7c2fb281dfea67c7e929985d3b1102b2df6 added support for `integer(kind=8)`.
This is fixed by using the correct type and kind.
Fixes #156, and may also fix #150.
=> Fix reading integer arrays from native phantom files

build/Makefile, src/utils/diffdumps.f90
Add a missing init call and LDFLAGS in makefile.
Needed to test if #159 applies to HDF5 outputs.
=> Add HDF5 support to diffdumps

src/main/utils_dumpfiles_hdf5.f90
Fix some trivial typos in HDF5 utils. Introduced in c21cf7c2fb281dfea67c7e929985d3b1102b2df6; these changes were probably not tested before committing.
=> Fix typos in hdf5 utils

build/Makefile, src/main/initial.F90, src/main/mpi_utils.F90, src/main/part.F90, src/main/readwrite_dumps_common.F90, src/main/sort_particles.F90, src/main/utils_dumpfiles.f90, src/main/utils_dumpfiles_hdf5.f90, src/main/utils_hdf5.f90, src/main/utils_sort.f90, src/tests/test_rwdump.F90, src/tests/utils_testsuite.f90, src/utils/diffdumps.f90, src/utils/libphantom-evolve.F90
Implement particle tracking for MPI by carrying the `iorig` array in MPI communications.
Change `iorig` to `int*8` as suggested by @danieljprice.
Particle order in the output files of MPI runs will in general be different, so `diffdumps` will not function correctly. This is fixed by sorting particles by ID prior to comparing arrays so that the same particles are being compared.
Needs #157 to function correctly.
Resolves #154.
=> Particle ID tracking for MPI

src/main/utils_dumpfiles.f90
singleprec is not initialised to .false., so double precision files may be incorrectly read as single precision, causing showarrays to print out junk values.
Resolves #163. The problem is not with the native phantom outputs themselves; it is caused by a bad reader. This problem did not arise with HDF5 outputs because an external HDF5 file reader was used to examine the values. This problem was not unique to sink particles; it affected all arrays.
=> Fix showarrays incorrectly reading files as single precision

src/main/force.F90, src/main/mpi_derivs.F90, src/main/mpi_force.F90
331970bfeb17423a92d3231b05d9c14a203c930b begins an MPI-enabled implementation for particle waking by carrying ibin_neigh in the cell back from remote tasks. 
However, it does not unpack and reduce the value on arrival. This causes ibin_neigh to be incorrect, and particle waking to be broken.
This was not picked up in the checks for #147 because the test suite does not check particle waking with MPI.
=> Finish implementing MPI for particle waking

src/main/centreofmass.f90, src/main/checksetup.F90, src/main/cooling.F90, src/main/energies.F90, src/main/force.F90, src/main/initial.F90, src/main/part.F90, src/main/ptmass.F90, src/main/ptmass_radiation.F90, src/main/random.f90, src/main/readwrite_dumps_common.F90, src/main/step_leapfrog.F90, src/tests/test_gravity.F90, src/tests/test_ptmass.F90, src/utils/analysis_clumpfind.F90, src/utils/analysis_common_envelope.F90, src/utils/analysis_protostar_environ.F90
Added algorithm to permit sink mergers.  They unconditionally merge if they pass with r_merge_uncond of one another, and will merge if they pass within r_merge_cond and they are bound.  By default, both radii are 0 to prevent mergers.  Once a particle as merged, its mass is set to negative; this has been accounted for throughout the code.
=> Sinks can now merge

src/main/cons2prim.f90, src/main/energies.F90, src/main/eos.F90, src/main/krome.f90, src/main/options.f90, src/main/part.F90, src/main/radiation_utils.f90, src/main/readwrite_dumps_common.F90, src/main/readwrite_dumps_fortran.F90, src/main/utils_tables.f90, src/setup/density_profiles.f90, src/setup/set_cubic_core.f90, src/setup/set_fixedentropycore.f90, src/setup/set_softened_core.f90, src/setup/setup_star.f90, src/tests/test_nonidealmhd.F90
- `eos_vars` can now store X, Z, and mu
- New option `use_variable_composition`
- `equationofstate` subroutine and certain eos-related subroutines now take mu as an optional input argument. If mu is not present, use the global variable `gmw` from the `eos` module instead.
- Can now set up a (core-softened) star with variable composition by reading X and Y from a MESA profile.
- Clean up modules related to softening stellar core profiles.
=> Allow variable composition (X, Z, mu)

.github/workflows/benchmarks.yml, .github/workflows/build.yml, .github/workflows/matrix_system.json, .github/workflows/test.yml
If a developer enables Actions on their fork, workflows that require custom runners or access to the central server will fail. This change prevents those parts from running by checking `github.repository == 'danieljprice/phantom'`.
Fixes #193
=> Disable Actions requiring custom runners on forks

src/main/part.F90
The allocation size for particle data `ipartbufsize` was increased by 2 in ed59ad73b5744266481219ba9a3e17c80680a7b0. This does not appear to do anything because the functions to fill and unfill the buffer were not updated. The arrays that this change accounts for (`dustproppred` and `ddustprop`) have size 2 each, totalling 4, so it was implemented incorrectly anyway.
Due to the mismatch, the code crashes when using MPI or reordering particles, due to the check `nbuf /= ipartbufsize`. This PR removes the change to `ipartbufsize`.
=> Fix ipartbufsize for dustgrowth

.github/workflows/benchmarks.yml, .github/workflows/build.yml, src/main/checksetup.F90, src/setup/setup_star.f90
**Type of PR:** other
**Description:**
#204 was intended to stop actions that required access to the custom runners from running on forks. All tests passed, but the behaviour of scheduled actions was not covered by the tests run on that PR.
When a scheduled action is run, the benchmark and build data is pushed to the central server, so this continues to fail on forked repos.
There is no need to run scheduled actions on forks - only when commits are made. This PR disables scheduled actions on forks.
**Testing:**
To test the scheduled actions, a test commit that reduced the scheduled interval to 15 minutes (Github's minimum) was pushed to the forked repo to verify that scheduled actions would be skipped.
**Did you run the bots?** yes
=> Disable scheduled actions on forks

AUTHORS, src/main/part.F90
Type of PR: 
Bug fix
Description:
#206 fixed a bug introduced by ed59ad73b5744266481219ba9a3e17c80680a7b0 where a feature was incorrectly implemented for MPI causing an error for non-dustgrowth runs by removing the change to the `ipartbufsize` counter. This fixed non-dustgrowth runs, but not dustgrowth runs.
The symptom is incorrectly calculated `dt` due to `graindens` being zero because `dustprop` and `dustproppred` are not transported between MPI tasks. The fix is to communicate those variables using MPI 
Testing:
The `growth` benchmark now runs to completion with MPI, whereas it previously did not. There is still no automated test for dustgrowth + MPI.
=> Copy dustprop and dustproppred between MPI tasks when moving particles

AUTHORS, src/main/evwrite.F90, src/main/part.F90, src/main/step_leapfrog.F90
Type of PR: 
Bug fix
Description:
`npartoftype` is used in some places, instead of `npartoftypetot`.
In `init_evfile`, the count of particle types is used to set `iquantities`. This variable is then used to loop over variables to perform `reduceall_mpi` on. If `iquantities` is not the same on each MPI task, some tasks perform an additional `reduceall_mpi` call, causing them to be mismatched and then hang when the last call is left waiting. Symptom: the code hung at a reduction call.
In `step`, `npartoftype` is used to calculate `ntypes`, which is used to set the switch `store_itype`. If some particle types are absent on a particular MPI task, the value of `store_itype` could differ. If `store_itype` is not true, then `itype` is not set. Symptom: when using dustgrowth, some dust particles …
=> Use npartoftypetot instead of npartoftype

AUTHORS, scripts/bots.sh, src/main/part.F90, src/utils/libphantom-evolve.F90
Type of PR: 
other
Description:
When `findent` is not available, `./bots.sh` gives an unhelpful error. This PR adds a friendly message to let the developer know that it is missing, and a link to install it, and then exits to prevent a partial bot run.
The requirement to install `findent` may be a barrier for some developers, causing them to not run the bots entirely. The option `-no-indent` runs all bots except for the indent bot. This option circumvents the `findent` requirement, with the aim of reducing the number of developers who don't run `./bots.sh` because of the requirement.
Testing:
./bots.sh run with `findent` installed and not installed.  Improved command line argument parsing tested by specifying `--no-indent --apply` and `--apply --no-indent` to verify commutativity and …
=> Indent bot warning

AUTHORS, scripts/bots.sh, scripts/pre-commit, src/main/part.F90, src/utils/libphantom-evolve.F90
Requires #212 
Type of PR: 
other
Description:
The bots take a long time to run (~30s), which may discourage developers from running them frequently. This PR adds the option `--staged-files-only` which runs the bot only on the files staged in git. This reduces the run time to as short as a few hundred milliseconds, making it suitable for a pre-commit hook.
A pre-commit script is included. To install:
```
cp scripts/pre-commit .git/hooks/
chmod +x .git/hooks/ pre-commit
```
On commit, the bots will automatically run on staged files. If changes have been applied, the commit will fail. Once the applied changes have been staged, the commit will succeed.
The benefit of using the pre-commit hook is that formatting changes are bundled into the commit containing the code change, rather than being …
=> Add option to run bots on staged files only

src/main/readwrite_dumps_fortran.F90
Type of PR: 
Bug fix
Description:
Increase particle memory allocation for MPI tasks to 3/n of the total number of particles. Some problems (e.g. dustgrowth) have a highly asymmetric particle distribution, and 2/n is not enough. Serial runs are not affected.
In the long term, dynamic memory reallocation should be implemented.
Testing:
MPI test suite
=> increase memory allocation for mpi tasks to 3/n

AUTHORS, src/main/mpi_utils.F90, src/main/part.F90, src/tests/test_gravity.F90
Type of PR: 
Bug fix
Description:
`directsum_grav`, the routine for calculating the gravitational force via direct summation is not MPI aware, and will give incorrect results when particles are distributed over multiple MPI tasks.
This PR shuffles all the particles onto the master task to calculate the direct summation, before allowing derivs to redistribute the particles across the MPI tasks. Care is taken to sort the particles by ID so that the test compares the results of the same particles.
Fixes #219 
Testing:
```
make MPI=yes DEBUG=no SETUP=testgrav OPENMP=no phantomtest
mpirun -n 4 bin/phantomtest gravity
```
=> MPI-compatible direct sum gravity test

AUTHORS, src/main/cooling.F90, src/main/eos.F90, src/main/ionization.f90, src/main/readwrite_dumps_fortran.F90, src/main/step_leapfrog.F90, src/main/timestep.F90, src/main/utils_indtimesteps.F90, src/setup/set_disc.F90, src/setup/set_sphere.f90, src/setup/set_unifdis.f90, src/setup/setup_star.f90, src/setup/setup_wave.f90, src/utils/analysis_common_envelope.F90
Type of PR: 
Multiple
Description:
Bug fix: Corrected explicit Koyama&Inutuska cooling
New Physics: added implicit Koyama&Inutuska cooling
Updated numerics: set_ellipse can now use random particle placement
Updated numerics: set_unifdis can use particle number rather than psep
Updated numerics: if dt < dtmax*0.5**maxbins, the exit will now occur in step after printing useful diagnostic info.
Bug fix/update: updated how dtmax can increase if dtmax is permitted to change with wall time
Testing:
These changes have been successfully used in test & production runs.
(Sorry for the multiple topics in a single PR; each topic is localised to a single commit)
=> Cooling, timing, & misc

.github/workflows/build.yml, .github/workflows/mpi.yml, .github/workflows/test.yml, scripts/buildbot.sh
Type of PR: 
other
Description:
The build check action makes each configuration sequentially. Currently there are 93 setups, so this takes about 3 hours to finish. This test slows down development pace because developers must wait a long time for checks on pull requests.
While waiting for build checks on my other PRs to finish, I parallelised the build action 😄
The maximum github action matrix size is 128. The tests cannot be run individually because all 93 tests have to be run for each compiler, >128. buildbot.sh has been modified to run setups in batches. It takes the argument
```
./buildbot.sh --parallel i j
```
where `j` is the number of batches to split the setups into, and the `i`'th batch is run. For example, `--parallel 2 10` will split the setups into 10 batches, and run the 2nd …
=> Parallel build action

AUTHORS, src/main/checksetup.F90, src/main/mpi_balance.F90, src/main/part.F90, src/tests/test_growth.F90, src/utils/libphantom-evolve.F90
Type of PR: 
Bug fix
Description:
The dustgrowth tests needed to be fixed as part of #217 . `test_farmingbox` was failing, and now passes.
Summary of fixes:
- `npartoftype` needs to be recalculated after balancing particles
- `npartoftype` was incorrectly used to calculate dust particle mass, changed to `npartoftypetot`
- `dustgasprop` needs to be carried during mpi exchange
Testing:
```
make MPI=yes SETUP=testgrowth phantomtest
mpirun -n 4 bin/phantomtest dustgrowth
```
=> Fix dustgrowth test with MPI

AUTHORS, src/tests/test_externf.f90
Type of PR: 
Bug fix 
Description:
The external forces test in test2 needed to be fixed as part of #217 
`npartoftype` was not defined during the problem setup, so the value is inherited from the previous test. `npartoftype(igas)` is used in `update_externalforce` for `make_beta_grids`. If the value is larger than the actual number of particles, junk values will be processed, resulting a crash when using `DEBUG=yes`. This is seen in [mpi #705](https://github.com/danieljprice/phantom/runs/5192077436).
Testing:
```
make MPI=yes SETUP=test2 DEBUG=yes phantomtest && mpirun -n 2 bin/phantomtest
```
Since full MPI tests have not yet been enabled (pending successful checks and merge of #217), the tests were performed on the ADACS fork: https://github.com/ADACS-Australia/phantom/actions/runs/18448 …
=> Fix test2 for external forces with MPI

AUTHORS, src/main/eos.F90, src/utils/libphantom-evolve.F90, src/utils/moddump_binary.f90, src/utils/moddump_recalcuT.f90
Type of PR: 
Minor functionalities and cleanup
Description:
* Cleanup of `moddump_binary` and generalise the ability to add a companion star from a second dump file.
* Change`moddump_recalcuT` to use eos parameters from input dump instead of relying on user input.
* Update `eosinfo` to print mean molecular weight, `gmw`.
Testing:
Code compiles for my setup and used it to set up a stellar binary.
Yes
=> moddump_binary

src/tests/test_ptmass.f90
Type of PR: 
Bug fix
Description:
Required for #217, discovered when `mpirun -n 4` was added
In ptmass.F90, during sink creation, whether the particle is at the potential minimum is checked:
```
! CHECK 7: particle i is at minimum in potential
if (poteni > potenj_min) then
ifail = inosink_poten
ifail_array(inosink_poten) = 1
endif
```
This check fails because an identical particle distribution gets created on every task, resulting in close comparisons when determining which particle to create a sink at.
This is fixed by only creating the particles on the master task, and allowing derivs to rebalance them.
`itest` needs to be calculated after calling derivs or else it will be incorrect. The `xcofm` calculation has been removed because the result is not used anywhere.
Testing:
```
make …
```
=> Fix sink potential check

src/tests/test_nonidealmhd.F90
Type of PR: 
Bug fix
Description:
Required for #217 
In a93bc90e41e7ad7e777d623b81fd6adeff097fd1, as part of implementing MPI support for nimhd tests, the L2 error variables were reduced across tasks.
There is a typo resulting in the `v_x` and `B_y` error being overwritten by the density error. This produces a test failure due to the tolerance not being met.
In df72df1c12c5588a17824ad6e78fe4c581a21e9f, NICIL 2.1 was added to phantom, where the tolerance for `B_y` was changed to `tolb=3.1d-2`. This was change was made possibly because the apparent improved accuracy was wrongly attributed to improvements to the code, rather than because the the density error was overwriting the `B_y` error.
`tolb` has been reverted to the original value of `1.1d-1`.
This bug is not yet covered by the …
=> Fix incorrectly reduced variables in nimhd test

AUTHORS, src/utils/diffdumps.f90
Type of PR: 
Description:
Return a non-zero exit code from diffdumps when the files differ.
This change is needed to resolve (along with https://github.com/phantomSPH/phantom-benchmarks/pull/15) https://github.com/phantomSPH/phantom-benchmarks/issues/14
Testing:
Benchmark tests: `./run-benchmarks.sh`
=> diffdumps: return a non-zero exit code if files differ

src/main/deriv.F90, src/main/initial.F90, src/main/metric_tools.F90, src/main/mpi_dens.F90, src/main/part.F90
Type of PR: 
Bug fix
Description:
- Recalculate the metric after moving particles to their new tasks
- Compute metric before prim2consall
- Make metricderivs an optional output of init_metric
- Transport GR variables using MPI
Testing:
Running full test suite via PR
=> Fix MPI support for GR

AUTHORS, src/main/externalforces.F90, src/main/step_leapfrog.F90
Type of PR: 
Description:
This hard accretion radius hack was introduced in https://github.com/danieljprice/phantom/commit/e54d7350c10c88c7e957227e995b2ff50cb3e3fe to test a scenario in response to a referee's request. It was merged into master, but is not useful in general. It also causes issues elsewhere because boundary particles can be created with no `massoftype set`. @dliptai and @danieljprice have agreed that it should be removed.
Testing:
Full test suite
=> remove accradius1_hard hack

src/main/dens.F90, src/main/force.F90, src/main/io.F90, src/main/linklist_kdtree.F90, src/main/mpi_balance.F90, src/main/ptmass_radiation.F90, src/main/quitdump.f90, src/utils/adaptivemesh.f90, src/utils/analysis_dustywind.F90
Type of PR: 
other
Description:
Performance optimisation: name every OMP critical section. There are many critical sections in MPI communication routines that can be run simultaneously. Because none of them are named, they block each other unnecessarily. Giving them names will prevent that.
Testing:
Full test suite
Did you run the bots? no, not required
=> Name every omp critical section

AUTHORS, src/tests/test_ptmass.f90
Type of PR: 
other
Description:
The tolerance of the angular momentum check for the circumbinary disc was set very close to the actual error value. Due to roundoff errors accumulated by MPI, this test can sometimes fail, e.g. https://github.com/danieljprice/phantom/runs/5383936672
The tolerance was adjusted from `3.e-7` to `4.e-7`.
Testing:
None; the change only loosens test suite tolerance.
=> Adjust tolerance of angmom test for circumbinary disc

AUTHORS, src/main/linklist_kdtree.F90, src/main/mpi_balance.F90
Type of PR: 
Description:
Optimisations to reduce unnecessary calls when compiling with `MPI=yes` but running with only 1 MPI task. This will allow the code to always be compiled with MPI enabled, even for pure OMP runs, with no loss of performance.
- Don't loop over all particles when balancing
- Don't build or walk global tree
Testing:
test suite
=> Optimisations for single task MPI

src/utils/moddump_binary.f90
Type of PR: 
Cleanup
Description:
Clean up `moddump_binary.f90`. 
Testing:
Used moddump to set up a sink-star-sink binary.
No
=> (moddump_binary) cleanup to improve code clarity

AUTHORS, src/setup/setup_blob.f90
Type of PR: 
Bug fix
Description:
Fixes #264
`npartx` is not initialised, so the default number of particles takes on a garbage value, resulting in non-deterministic behaviour. This is often larger than `maxp`, causing the setup to fail in the build suite.
Default value set to 100.
Testing:
Run `./phantomsetup` repeatedly and ensure the same output is created.
=> bugfix: initialise npartx

AUTHORS, build/Makefile_qscripts
Type of PR: 
other
Description:
`make MPI=yes test` runs with `NMPI` tasks. Changing the default to 4, since that is the typical number of cores on a laptop workstation. Running with 8 tasks on machines that have less than 8 cores will require oversubscribing tasks.
Testing:
`make MPI=yes test`
=> change default NMPI to 4 in Makefile

AUTHORS, src/main/force.F90, src/main/kdtree.F90, src/main/linklist_kdtree.F90
Type of PR: 
Description:
The switch for determining whether f_grav needs to be calculated is convoluted and depends on the GRAVITY pp flag. This makes the code hard to understand. This change simplifies the logic, without affecting performance.
Testing:
Test suite with and without MPI
=> Refactor gravity switch for force and getneigh

src/setup/relax_star.f90
Type of PR: 
Bug fix (closes #281)
Description:
See title. The previous code allocates `2*npart` to create buffer for relax_star. We now limit this to `maxp`.
Testing:
Set up a star with `relax_star` when maxp < 2*npart
No
=> (relax-star) do not allow buffer memory allocation to exceed maxp

src/utils/moddump_rotate.f90
Type of PR: 
New moddump
Description:
New moddump sets solid body rotation for all gas particles about the z-axis given angular frequency. Let me know if this function already exists or should be placed in an existing module.
Testing:
Compiled successfully with SETUP=star, used to produce a spinning star.
No
=> Moddump for adding solid body rotation to gas

src/main/ptmass.F90, src/setup/setup_star.f90, src/tests/test_ptmass.f90
Type of PR: 
Description:
For two of my projects, sinks were failing to form when they should.  This code adds an (optional) override to force sink creation when rho > rho_crit*f_crit_overrride.  Although required, this is a dangerous algorithm since forcing sink creation may hide other issues, so it must be turned on manually in ptmass.F90 by setting f_crit_overrride > 0.  If this is set, then f_crit_override will appear in the .in file.  
Testing:
Tested via toy model.  Using a hydro sphereinbox sim, too high of f_crit_overrride fails since we have multiple dense particles wanting to form and we still stop with dt < dt_min, too low of f_crit_overrride will yield artifical results, and just the right f_crit_overrride will yield convergence (achieved in my …
=> (ptmass) added an override to force sink creation if density is too high

build/Makefile, src/main/eos.F90, src/main/eos_stratified.f90, src/setup/setup_disc.f90, src/tests/test_eos.f90, src/tests/test_eos_stratified.f90
Type of PR: 
Added in separate modules for running and testing the temperature stratified equation of state, now also includes Dartois et al. (2003) prescription which matches mid plane temperature
Description:
Added in separate modules for running and testing the EOS, and modified the Makefile to include these, the setup_disc routine to contain relevant parameters, and the eos.F90 and test_eos.f90 files to call to the new functions
Testing:
Passed entire test suite and eos test suite
=> Stratified EOS - Law and Dartois prescriptions

src/main/readwrite_dumps_hdf5.F90, src/main/utils_dumpfiles_hdf5.f90
Type of PR: 
Fixed some files that were preventing phantom2hdf5 from being compiled.
Testing:
I successfully compiled phantom2hdf5 and was able to use it to turn PHANTOM dumps into usable .hdf5 files
Did you run the bots?
Yes.
=> Fixed phantom2hdf5 not compiling

AUTHORS, src/main/cons2prim.f90, src/main/cooling_molecular.f90, src/main/dust_formation.F90, src/main/eos.F90, src/main/eos_stratified.f90, src/main/initial.F90, src/main/mpi_balance.F90, src/main/ptmass.F90, src/main/ptmass_radiation.F90, src/main/readwrite_dumps_common.F90, src/main/readwrite_dumps_fortran.F90, src/main/utils_shuffleparticles.F90, src/setup/setup_disc.f90, src/tests/test_eos.f90, src/tests/test_eos_stratified.f90, src/utils/libphantom-evolve.F90
**Type of PR:** 
**Description:**
In the existing implementation of `balancedomains`, `recv_part` is called after checking if a particle belongs to a task to check if a particle is waiting to be received. Checking if a particle belongs to a task is an integer comparison, which is fast relative to performing `MPI_Test` within `recv_part`. 
These repeated `MPI_Test` calls present significant overhead and do not need to be called so frequently. This problem is made worse when `MPI_THREAD_MULTIPLE` is enabled (namely for upcoming optimisation #310), because MPI calls have an additional small overhead.
In this PR, the loop is changed to only call `recv_part` every `check_interval` iterations. `check_interval` is dynamically adjusted based on the frequency of …
=> Particle balance optimisation

.pre-commit-config.yaml, scripts/bots.sh
Type of PR: 
Bug fix
Description:
- Creation of the AUTHORS file is not threadsafe, so parallel pre-commit cannot be used. Set `require_serial: true`
- Update `.pre-commit-config.yaml` formatting
- Only the first file being passed through using the `--file` option was being processed. Now takes a list of files
- Only run with the subset of files that would be run if the full `bots.sh` script was being run
- Optimisation to remove unnecessary calls to `get_only_files_in_git()`, because files are already in git (or will be in git) if they are being handled by pre-commit.
Testing:
Source files were manually changed to violate the bots rules, and confirmed that this blocked the commit. Run time is only a few seconds, which shows that the script is only being run on the relevant files.
Did you …
=> Fixes to the bots.sh pre-commit action

.github/workflows/benchmarks.yml
Type of PR: 
other
Description:
The phantom-dev Nectar project has not been renewed, so the custom runners for performing benchmarks are not available. This causes checks to hang until they time out. Although benchmarks are not required to merge PRs, this creates confusing behaviour. The benchmark triggers have been disabled until the project is renewed.
Testing:
No testing
=> disable benchmarks action

src/main/mpi_memory.F90
Type of PR: 
Bug fix
Description:
Safety factor was hardcoded as `4` instead of being used from the parameter value. This fix does not change results.
Testing:
No tests
=> bugfix: safety factor for stacksize calculation

build/Makefile, src/main/mpi_memory.F90, src/tests/test_mpi.F90, src/tests/testsuite.F90
Type of PR: 
Additional tests
Description:
Added some MPI unit tests to the testsuite
=> Mpi testsuite

src/main/cooling_solver.f90, src/setup/setup_shock.F90
Type of PR: 
Bug fix
Description:
when cooling is zero, e.g. using the piecewise cooling function, variables in implicit cooling become undefined
Testing:
tested on shock tube
Did you run the bots? no need, just been done
=> fix bug in implicit cooling when du/dt goes to zero

src/setup/phantomsetup.F90
Type of PR: 
Bug fix
Description:
As per tbdrstl on Slack, this is a bug patch when running phantomsetup using MPI.  @danieljprice , is there a reason that init_mpi and associated commands are so far down in phantomsetup?  The other patch would be to move the init_mpi commands to the top above set_io_unit_numbers, but I am unsure if this would cause other issues... 
Testing:
Compiled & test ran phantomsetup
=> (phantomsetup) Bug fix when using MPI

src/setup/set_star.f90, src/setup/setup_star.f90
Type of PR: 
Bug fix & modification to existing code
Description:
Add line in setup_star to set gas and radiation temperatures to be equal when do_radiation=.true.
Also, removed hard-wiring hsoft = 0 despite non-zero value specified in .setup file.
Testing:
Set up stars both using SETUP=star and SETUP=radstar
No
=> (star) set up star in simulation with radiation

build/Makefile, build/Makefile_systems, src/utils/analysis_common_envelope.F90
Type of PR: 
Bug fix
Description:
PHANTOM would previously not compile on computers that used aarch64 CPUs (at least when SYSTEM=gfortran) so I fixed the issue that was causing this (which was that mcmodel=medium is not a valid option for gfortran on aarch64 processors).
Testing:
I successfully compiled and ran the test suite on two computers that used aarch64 processors where SYSTEM=gfortran.
=> Made compiling with gfortran on aarch64 processors possible.

src/utils/analysis_common_envelope.F90
Type of PR: 
Description:
I added two new options to analysis_common_envelope.F90; one that calculates information regarding Kelvin-Helmholtz based planetary destruction (from https://arxiv.org/abs/1210.0879) and another that creates binding energy profiles for the star (both including and excluding internal energy).
Testing:
I checked that the output of these new options have valid data.
=> Added planetary destruction option and binding energy profile option to analysis_common_envelope.F90.

src/utils/moddump_binary.f90
Type of PR: 
Description:
When using the "Set up a binary system with a star from another dumpfile" option in the binary moddump, particles from star 1 have to be stashed in the particle arrays so they don't get overwritten from reading the dump containing star 2. This is only doable if maxp > 2*nstar1 (at least if nstar1>nstar2). Display an error message and remind the user to increase MAXP when this condition is not satisfied.
Testing:
Used this code.
No
=> (moddump-binary) add error message if maxp too small to duplicate star 1

src/main/dust_formation.F90, src/main/part.F90
Type of PR: 
Bug fix
Description:
the arguments of call get_temperature in dust_formation.F90 were not in the right order!
Testing:
not tested
Did you run the bots? 
no
=> (dust_formation) wrong argument order in call get_temperature

src/utils/moddump_sink.f90
Type of PR: 
other
Description:
small change to allow giving of --maxp=2000000 as a command line flag to phantomsetup, avoiding the need to recompile to allocate memory
Testing:
./phantomsetup --maxp=2000000 works
=> give --maxp as flag to phantomsetup

build/Makefile, build/Makefile_setups, src/main/damping.f90, src/main/dust_formation.F90, src/main/eos.F90, src/main/eos_stratified.f90, src/main/initial.F90, src/main/inject_steadydisc.f90, src/main/io.F90, src/main/options.f90, src/main/readwrite_dumps_fortran.F90, src/main/readwrite_infile.F90, src/main/step_leapfrog.F90, src/main/utils_shuffleparticles.F90, src/setup/set_disc.F90, src/setup/setup_planetdisc.f90, src/tests/test_poly.f90, src/utils/moddump_sink.f90, src/utils/showarrays.f90
Type of PR: 
new physics
Description:
implementation of "wave-killing" boundary zones for disc simulations, idamp=3
Testing:
simulation of accretion disc that does not accrete: seems to hold disc profile steady between the boundaries
Caveats:
- currently assumes M=1, mainly useful for disc with external potential
- velocity is damped to purely Keplerian profile, not accounting for pressure gradient
- radius is relative to the origin, so assumes centre of mass is at the origin
=> Damping bcs

src/main/options.f90, src/main/readwrite_infile.F90, src/utils/analysis_mcfost.f90
Type of PR: 
other
Description:
Added two additional input options when compiling with MCFOST=yes
- mcfost_keep_part -- Fraction of particles to keep for MCFOST
- ISM -- ISM heating : 0 -> no ISM radiation field, 1 -> ProDiMo, 2 -> Bate & Keto
Testing:
I compiled with MCFOST=yes and ran a quick test simulation
=> Adding two addition input options with MCFOST=yes

src/setup/setup_disc.f90
Type of PR: 
Modification to the `disc` setup type to allow the following configurations:
- A system with 4 sink particles (double binary), with a circumbinary disc around the first hierarchical level secondary.
- A system with 3 sink particles, with a circumbinary disc around the first hierarchical level secondary. 
Description:
- Variables added to define the orbital parameters of the second binary.
- Two new variables, `discpos` and `discvel` defined to  set the  position and velocity of the disc. This was needed so the disc could be centred on a binary that is not located at the origin, rather than the centre-of-mass of the entire system.
- `set_multiple` subroutine call added to set up a second binary. 
- Command line prompts updated to include new configurations.
The last 2 rows of …
=> Enable adding 4 sink particles to a disc setup

AUTHORS, src/tests/test_fastmath.F90, src/tests/test_kernel.f90
Type of PR: 
Bug fix
Description:
There are a handful of tests which write part of the log to stderr. The majority of tests in the suite write to stdout, so they have all been changed to stdout for consistency.
Testing:
Running test locally, splitting stdout and stderr to identify erroneously written log lines.
Did you run the bots? yes, via pre-commit
=> Fix: test output being written to stderr

build/Makefile, src/main/cooling.F90, src/main/cooling_gammie_PL.f90
Possibility to have a Gammie \beta cooling as a function of the radius (power law).
2 new parameters: 
1) eta, that is the exponent of the power law (r^-eta)
2) r_beta, the characteristic radius at which the beta_cooling is fixed
=> Add possibility of varying beta cooling with radius as a power law

src/utils/moddump_addflyby.f90
Moddump to add a flyby to an evolved simulation (sink particle in parabolic orbit).
- asks the same parameters as setup flyby
- gives as output the time in code units to put in the new *.in file
- tested
=> new moddump addflyby

build/Makefile, src/main/readwrite_dumps_hdf5.F90, src/main/utils_dumpfiles_hdf5.f90
Type of PR: 
Bug fix
Description:
Fixed various issues preventing the compilation of phantom2hdf5 and also added some missing got arrays (x, z, mu and nucleation) for the reading of hdf5 files.
Testing:
I successfully compiled phantom2hdf5 and made a readable .h5 file using it. I did not test the got arrays that I added.
=> Fixed problems with phantom2hdf5 not compilling and added missing got arrays for the reading of hdf5 files.

src/main/force.F90, src/main/growth.F90, src/tests/test_growth.F90
Dust growth: mass-weighted interpolations of dust-gas quantities are now default, option removed
Type of PR: 
Modification to existing code
Description:
Option to interpolate dust gas quantities such as gas density or sound speed by mass or mass/density when using dust growth has been removed. Mass weighted interpolations are more accurate than mass/density interpolations.
It was not needed to keep the mass/density weighted interpolation in the code, and thus was removed. 
_Left: Radial profiles of sound velocity interpolation for two different methods (red: mass weighted, blue: mass/density weighted). Right: Interpolation of the sound speed on each dust particle for two different methods. The profiles in the left panel are calculated from the distributions in the right panel by averaging …
=> Dust growth: mass-weighted interpolations of dust-gas quantities

src/utils/moddump_extenddisc.f90, src/utils/moddump_sphNG2phantom.f90, src/utils/moddump_sphNG2phantom_addBfield.f90, src/utils/phantomanalysis.f90
Type of PR: 
other
Description:
the default setting of hfact=1.2 is ok for the cubic spline but not if a different kernel is employed. Hence we should not have any hardwired hfact=1.2 statements in the code. This replaces those remaining with hfact=hfact_default where hfact_default is a parameter in the top of the corresponding kernel module.
Testing:
compiled phantomanalysis and moddump with the amended files
=> (hfact) remove remaining hardwired hfact=1.2; replace with hfact=hfact_default

src/main/eos.F90, src/main/radiation_implicit.f90, src/main/radiation_utils.f90, src/main/readwrite_infile.F90, src/setup/relax_star.f90
Type of PR: 
Bug fix
Description:
- Using relax_star with do_radiation = .true. requires setting rad=0.
- Use integer runtime option cv_type to specify method to calculate mean molecular weight in get_1overmu and in get_cv. For cv_type = 0, use mu = gmw and cv = Rg/((gamma-1.)*gmw*unit_ergg). For cv_type = 1, use MESA tables. 
Testing:
Set up radiating star.
no
=> (radiation) make cv_type runtime option and set rad=0 in relax_star when using radiation

src/main/readwrite_dumps_fortran.F90
Type of PR: 
Bug fix
Description:
Removed 4 lines in readwrite_dump_fortran.f90 preventing simulations with more than 2 dust species to run.
Testing:
Multigrains (5 dust species) simulation started without any problems as well as the dustyshock test.
=> Removed lines in readwrite_dump preventing multigrains simulations to run

src/setup/relax_star.f90, src/setup/set_star.f90, src/setup/setup_star.f90, src/utils/moddump_binary.f90
Type of PR: 
- Bug fix
Description:
- `set_star_thermalenergy` now takes `npts` as an input so that density and pressure arrays can be interpolated in their valid range. This fixes the bug where array interpolation gives den = pres = 0, e.g., when setting up a polytrope with `relax_star = .false.`.
- Reorganisation of `moddump_binary` that fixed some bugs. Now tested that setup = 1, 8 options work for producing 6 possible types of binary stars: 1) star+star, 2) sink-star+star, 3) star+sink-star, 4) sink-star+sink-star, 5) sink-star+sink, 6) star+sink.
=> Bug fixes related to star and binary star setup

build/Makefile, src/main/checksetup.F90, src/main/io.F90, src/setup/density_profiles.f90, src/setup/phantomsetup.F90, src/setup/relax_star.f90, src/setup/set_fixedentropycore.f90, src/setup/set_star.f90, src/setup/set_star_kepler.f90, src/setup/set_star_mesa.f90, src/setup/setup_grtde.f90, src/setup/setup_star.f90, src/utils/moddump_binary.f90
Type of PR: 
Bug fix / cleanup
Description:
This is a cleanup of the setup_star procedure, containing the following changes:
major:
- moved read_mesa and read_kepler_profile into separate modules containing
functionality for read/write of mesa and Kepler files
minor:
- uncluttered warnings, in particular added line spaces before and after ALL warnings in phantom
- added warning if the relaxation procedure in setup_star did not converge
- setup_star now dies if it fails to read the MESA EOS tables, instead of seg faulting
- fix build failure in phantomsetup due to set_hierarchical (if make setup typed before make)
- make all warnings in checksetup emit "ERROR: " or "WARNING: " to make them more obvious
- only print the centre of mass from checksetup if there are no warnings or errors, to …
=> (setup_star): unclutter warnings; warn if relaxation not converged

src/main/force.F90, src/main/readwrite_dumps_fortran.F90
Type of PR: 
- Bug fix + feature
Description:
- Explicit radiative diffusion now selects whether or not to use the (Levermore & Pomraning) flux limiter depending on the input option `limit_radiation_flux`. Previous behaviour was to always use an optically-thick diffusion coefficient (lambda->1/3), which is a bug. Can @danieljprice check if this change is safe for implicit radiative diffusion?
- readwrite_dumps modified to also read grad(E) and lambda from a dump that used radiation.
=> (radiation) control flux limiter with switch; read additional radiation quantities from dumps

build/Makefile, src/setup/relax_star.f90, src/setup/set_cubic_core.f90, src/setup/set_softened_core.f90, src/setup/set_star.f90, src/setup/set_star_mesa.f90, src/setup/set_star_utils.f90, src/setup/setup_star.f90, src/utils/moddump_binary.f90
Type of PR: 
cleanup / structural changes to set_star
Description:
The aim of this change is to be able to perform all the functionality of setup_star from any setup routine in phantom. This is with the intention of making several "two-step" setup-and-moddump procedures into a single, streamlined procedure. For example, the TDE setup could add a star, relax the star and place it into orbit without needing the moddump procedure. Similarly, this change allows implementation a binary, triple or hierarchical star setup with multiple stars read from MESA tables.
The changes to the code at the moment are purely structural, there is no change in functionality:
- added new set_star routine/module that does all the steps in setup_star
- set_star provides routines to read/write/ask for all the …
=> (set_star) shifted all the work in setup_star into set_star routine

.github/workflows/mcfost.yml
Type of PR: 
continuous integration testing, closes #379 
Description:
this is a GitHub action to compile phantom and link it against MCFOST, as needed for live phantom+mcfost simulations
the idea is to check if the API gets broken for whatever reason (could either be at the phantom or on the mcfost end).
Testing:
Will be tested in the actions workflow
Did you update relevant documentation in the docs directory? yes, the action follows recommended installation procedure for homebrew installation of mcfost in the mcfost help page
=> GitHub actions workflow to check phantom+mcfost

AUTHORS, build/Makefile, build/Makefile_setups, src/main/checksetup.F90, src/main/externalforces_gr.F90, src/main/metric_schwarzschild.f90, src/main/options.f90, src/setup/relax_star.f90, src/setup/set_binary.f90, src/setup/setup_grtde.f90, src/tests/test_gr.F90, src/utils/analysis_kepler.f90, src/utils/moddump_tidal.f90, src/utils/utils_orbits.f90
Type of PR: 
improved setup procedure
Description:
Cleanup of the setup procedure for tidal disruption events in General Relativity. Previously this required compiling with SETUP=grstar and then moddump using moddump_tidal.f90
Now, setup_grtde calls the new general set_star procedure to setup and relax a star. To avoid the need to switch metrics we simply set M=0 in the Kerr or Schwarzschild metric during relaxation, effectively giving a Minkowski metric during the stellar relaxation  procedure
I also corrected an issue where we had set ireconav = 1 by default in the .in file for GR simulations, which is problematic if anything gets too close to the black hole. Hence the default setting is now ireconav=-1. This fixes #333
Testing:
1000 particle GR tidal disruption event with polytrope …
=> setup for tidal disruption event in GR

src/utils/moddump_dustadd.f90
Type of PR: 
Bug fix
Description:
Correct a bug preventing the initialization of dust properties in 1 fluid with dustgrowth in moddump_dustadd.
The initialization of the dust properties couldn't be done because the routine was in the loop for 2 fluids only.
Testing:
Add dust to a gas simulation in one fluid with moddump_dustadd.
=> Correct a bug preventing the initialization of dust properties in 1 fluid with dustgrowth in moddump_dustadd

build/Makefile
Type of PR: 
Build failures fixed, closes #292 and #293 
Description:
A bunch of phantom utilities fail to compile using ifort on Mac OS, with typical errors like:
```
Undefined symbols for architecture x86_64:
"_options_mp_alpha_", referenced from:
_readwrite_dumps_fortran_mp_fill_header_ in libphantom.a(readwrite_dumps_fortran.o)
_readwrite_dumps_fortran_mp_write_smalldump_fortran_ in libphantom.a(readwrite_dumps_fortran.o)
_readwrite_dumps_fortran_mp_write_fulldump_fortran_ in libphantom.a(readwrite_dumps_fortran.o)
_readwrite_dumps_common_mp_check_arrays_ in libphantom.a(readwrite_dumps_common.o)
"_options_mp_alphab_", referenced from:
_readwrite_dumps_fortran_mp_fill_header_ in libphantom.a(readwrite_dumps_fortran.o)
_readwrite_dumps_fortran_mp_write_smalldump_fortran_ in …
```
=> (build) fix a bunch of weird link failures with ifort on Mac OS

src/main/energies.F90, src/main/units.f90, src/setup/set_star.f90
Type of PR: 
new warning + star mass and radii now always specified in solar radii
Description:
- read mass and radius for polytropic stars in solar mass and solar radii rather than code units, this is particularly helpful for GR
- warns the user about stars being too small for weak field gravity to be valid
- fix a small bug where total mass in particles was not computed in GR code
For example, if one naively chooses default values M=R=1 in code units when using the GR code this produces a star smaller than its Schwarzschild radius, giving errors like the following when you run phantom:
```
WARNING! cons2primsolver [in step_extern_sph_gr (a)]: enthalpy did not converge on particle 1
WARNING! cons2primsolver [in step_extern_sph_gr (a)]: enthalpy did not converge on particle 836
``` …
=> (#402) added warning if R < 6GM/c^2 for star in GR

build/Makefile_setups, scripts/bots.sh, src/main/utils_datafiles.f90, src/main/utils_filenames.f90, src/setup/set_star.f90, src/setup/setup_solarsystem.f90, src/utils/moddump_rad_to_LTE.f90, src/utils/utils_ephemeris.f90, src/utils/utils_mpc.f90
Type of PR: 
added planets to the solar system setup
Description:
Can now download ephemeris files for the planets in the solar system and add them to the orbits of the minor bodies
Testing:
make SETUP=solarsystem
./phantomsetup solarsystem
=> Solar system

src/setup/setup_grtde.f90
Type of PR: 
Bug fix (thanks to Martina Toscani for reporting)
Description:
Mass and radius of star in .setup file for SETUP=grtde was messed up because of incorrect unit conversions
Testing:
```
make SETUP=grtde
./phantomsetup grtde
```
this works now without getting very small values of Mstar and Rstar in the .setup file. The issue was that for the GR setup the central mass needs to be 1 in code units, but we take mhole as an input parameter, so the units need to be set immediately AFTER mhole is read, but BEFORE the star options are read from the .setup file.
=> (grtde) BUG FIX with units in GR tidal disruption event setup

src/main/eos.F90
Type of PR: 
Bug fix
Description:
The Farris generalised equation was using a radius instead of a mass in the summation
Testing:
None, obvious bug.
=> (eos) bug fixed in generalised Farris eos 13

build/Makefile_setups, scripts/bots.sh, src/main/extern_binary.f90, src/main/extern_binary_gw.f90, src/main/externalforces.F90, src/main/utils_datafiles.f90, src/main/utils_filenames.f90, src/setup/set_star.f90, src/setup/setup_chinchen.f90, src/setup/setup_disc.f90, src/setup/setup_gwdisc.f90, src/setup/setup_planetdisc.f90, src/setup/setup_solarsystem.f90, src/utils/moddump_rad_to_LTE.f90, src/utils/utils_ephemeris.f90, src/utils/utils_mpc.f90
Type of PR: 
Fix for #429 
Description:
Removed the binarymassr parameter and implemented m1 and m2 as input parameters directly
Testing:
Checked compilation of all routines
=> Binary potential uses m1 and m2

src/main/utils_filenames.f90, src/setup/readwrite_mesa.f90, src/setup/set_star.f90
Type of PR: 
Bug fix
Description:
Generalised the MESA star reader to ingest stellar profiles supplied by Ross Church from the Eggleton stellar evolution code. Changes merely make the MESA reader a bit more general without breaking existing functionality:
- made the read_mesa routine used in set_star able to read any file written by a stellar evolution code as long as it is in labelled columns, e.g.
```
0.   0.  1e-6 1e-7
0.1 0.1 1.1e-6 1.1e-7
``` 
- column label recognition now uses same routine used in splash which is quite general and handles labels written in a variety of formats
- allow more generous interpretation of labels e.g. pressure or p both work for the pressure column
- automatically detect whether the file is written in reverse or forward order, rather than presuming …
=> (set_star/mesa) read any tabulated stellar profile using iprofile=5 in set_star

src/setup/set_binary.f90, src/setup/setup_binary.f90
Type of PR: 
minor fixes to information printed out for hyperbolic/parabolic orbits (#302)
Description:
semi-major axis printed negative for hyperbolic orbits; period is printed as huge() for parabolic/hyperbolic orbits
Testing:
```
~/phantom/scripts/writemake.sh binary > Makefile
make setup
./phantomsetup orbit
```
=> (set_binary, #302) minor fixes so printouts obey conventions

src/main/forcing.F90
Type of PR: 
Bug fix 
Description:
Turbulent stirring had the ifdef STIR_FROM_FILE removed in commit 7c86f4e. One set of ifdef statements were missed. This would cause the turbulent stirring to try to not stir from file. Now all STIR_FROM_FILE ifdef statements are removed, instead using the logical parameter.
Testing:
Before and after test on SETUP=turb. Previously would error the first time the code tried to force.
Did you run the bots? N/A
Did you update relevant documentation in the docs directory? N/A
=> Remove leftover ifdef statements to fix stirring bug

build/Makefile, src/main/radiation_implicit.f90, src/main/utils_deriv.f90, src/main/utils_implicit.f90, src/main/utils_timing.f90, src/tests/test_radiation.f90
Summary of changes:
- Iterate only over subset of particles that have not converged.
- Lower `tol_rad` from 10^-5 to 10^-6 in test suite so that calculation of dxi/dt with implicit radiation is accurate enough when iterating over individual particles. 
- Move allocation of compacted neighbour list and neighbour arrays into new module `implicit` (utils_implicit.f90).
- Only allocate arrays if unallocated, as opposed to doing so every time step.
- Remove calculation of redundant dvdx in `fill_arrays` (it is identical to the calculation in density). Remove check for `dvdx` in the test suite.
- Put calculation of flux limiter lambda and Eddington factor into the `compute_flux` particle loop. Remove timing for computing lambda and eddington.
- Cache cv, lambda, eddington, and opacity in …
=> Optimise implicit radiation solving

.github/workflows/build.yml, build/Makefile_defaults_ifort, build/Makefile_systems, docs/disc.rst, docs/flatiron.rst, scripts/buildbot.sh
Type of PR: 
Bug fix
Description:
ifort -v give a multi-line output on this cluster, resulting in an error determining the ifort version, this is now fixed in the default options for the ifort compiler
Testing:
compile phantom with SYSTEM=rusty on the flatiron cluster
Did you update relevant documentation in the docs directory? yes...
=> (build) fix issues with SYSTEM=rusty

src/setup/set_disc.F90
Type of PR: 
Bug fix
Description:
Added radius grid in dust calculation.
Testing:
One-fluid dust disc setup is now running without NaN errors.
=> BUGFIX - fixes #434

src/utils/analysis_common_envelope.f90
Type of PR: 
Bug fix 
Description:
Fix NaN values in Roche option in CE_analysis
Testing:
Comparing the generated .ev files
=> Fix NaN values in Roche option in CE_analysis

src/utils/analysis_dustformation.f90
Type of PR: 
new analysis routine
Description:
Analysis routine analysis_dustformation.f90 computes the time at which dust formation commences on each SPH particle and writes the results to a .comp file that is readable by splash as an extra column
Testing:
./phantomanalysis light_????? on Luis Bustamante-Bermudez's simulations
=> (analysis_dustformation) analysis routine to compute time of dust formation

build/Makefile_setups, src/main/inject_BHL.f90, src/main/inject_windtunnel.f90, src/setup/set_star_utils.f90, src/setup/setup_binary.f90, src/setup/setup_windtunnel.f90
New setup and injection module "windtunnel" for gas polytrope in a windtunnel. Input parameters include wind speed, wind pressure, wind density, sphere radius, and sphere mass.
- Note that I have changed the logic of `set_star_density` to "know" `mass_is_set = .true.` when `massoftype(igas) > tiny(0.)` (indifferent to the value of npart). This is needed for the wind tunnel, where the particle mass must be known and set before setting up the star, so that the wind can be initialised. An implication of this is that `massoftype` should not be initialised to zero in `setup_binary`, which seems to be unnecessary anyway.
Future work:
- Generalise the gas polytrope to any "star" that can already be set up using the `setstar` module
- Allow for arbitrary EoS, which is currently hard-wired to be …
=> Wind tunnel setup and injection module

src/main/force.F90
Add contribution of radiation pressure to signal speed when using radiation (e.g., Eq 10 in https://arxiv.org/abs/1102.1216). We should have cs = (5/3*Pgas/rho + 4/3*Prad/rho)^1/2. Otherwise, tcour may be underestimated.
=> Signal speed used in tcour should include radiation pressure

src/main/inject_asteroidwind.f90, src/setup/setup_asteroidwind.f90
Type of PR: 
Bug fix
Description:
Fix assignment of particle mass in the asteroid wind setup from Trevascus et al. (2021). The particle mass must be set during the setup procedure based on the mean mass injection rate and the desired tmax and number of particles at max.
Fixes #463
Testing:
```
~/phantom/scripts/writemake.sh asteroidwind > Makefile
./phantomsetup wind
./phantom wind
```
=> (#463) bug fixes with particle mass setting in asteroidwind

src/setup/setup_shock.F90
- Interactive setup now prompts for mass and length units
- Units now written into and read from setup file
=> Set units for shock setup

src/utils/analysis_common_envelope.f90
Type of PR: 
Description:
Testing:
=> Add v_esc option for .divv files

src/setup/set_star.f90
Type of PR: 
Bug fix 
Description:
fix bug in set star with undefined need_iso
Testing:
make SETUP=binary
./phantomsetup crap
=> fix bug in set star with undefined need_iso

src/main/readwrite_dumps_fortran.F90
Type of PR: 
Bug fix 
Description:
Bug fix reading dumps created with shamrock code, where there is only one block, or with MHD arrays in block 1 instead of block 4
Testing:
successfully read shamrock output in phantom format
=> (shamrock) fix compatibility issues reading dump file 

src/setup/set_star.f90, src/utils/moddump_LTE_to_rad.f90, src/utils/moddump_rad_to_LTE.f90
Tested that using moddump_LTE_to_rad and moddump_rad_to_LTE in succession recovers the same dump file to within machine precision.
=> New moddump that converts non-radiative dump to radiative dump

src/main/readwrite_infile.F90, src/utils/moddump_LTE_to_rad.f90
User should be able to set X and Z mass fractions assumed by MESA tables instead of the code default values.
=> Read X and Z mass fractions when using radiation with MESA opacity tables

src/main/eos.f90, src/main/eos_gasradrec.f90, src/main/eos_idealplusrad.f90, src/tests/test_eos.f90, src/tests/utils_testsuite.f90
- Add optional flag to force checkvalbuf_real to use relative instead of absolute tolerances.
- Require tolerance of 1e-15 for ieos=12 (ideal gas+rad) forward-backward test. Previous tolerance was 1e-12.
- Tighter tolerance of ieos=20 (gas+rad+rec) temperature solving from 1e-13 to 1e-15. Adjust tolerance for forward-backward test for ieos=20 from 1e-12 to 1e-14 (it does not have an error < 1e-15 and I don't know why).
=> tighter tolerances for ieos=12,20 testing

src/tests/test_derivs.F90
Type of PR: 
Bug fix in derivs testsuite if run with non-periodic boundaries and MHD, also cleanup ifdefs in test_derivs (#55)
Description:
Fix #529 
Testing:
make SETUP=disc phantomtest && ./bin/phantomtest derivs
=> Derivs test bug

src/main/dust_formation.f90
Type of PR: 
Bug fix 
Description:
when using ieos=2 with nucleation,  a discontinuity was present in the profile of gamma (polytropic index) due to an error in its formulation. 
Testing:
the new wind profiles do not show the discontinuity in gamma anymore
=> (dust_nucleation) fix calculation of gamma

src/main/checkconserved.f90, src/main/energies.F90, src/main/evolve.F90, src/main/force.F90, src/main/options.f90, src/main/readwrite_infile.F90, src/setup/setup_sphereinbox.f90
Type of PR: 
Bug fix 
Description:
attempted timestep control based on hdivBonB lowers the timestep but did not change the cleaning speed, hence we have removed this functionality. Instead overcleanfac should be set manually if divB is large.
Testing:
Current loop advection, test magnetized discs.
=> removing hdivB timestep constraint as did not work

build/Makefile_setups, scripts/buildbot.sh, src/main/checksetup.f90, src/main/deriv.F90, src/main/utils_infiles.f90, src/setup/setup_grtde.f90
Type of PR: 
Bug fix
Description:
Fix to #543 and #465. 
For #543, the problem is that MAXP should no longer be hardwired in the compile-time configuration block. Instead, it can be specified at  runtime using
```
./phantomsetup star --maxp=1e8 
```
In phantom the memory allocation is automatic as the number of particles is read from the dump file header. This should be ideally be done automatically also in phantomsetup but this is currently not the case, as memory allocation  is done before entering the setpart routine
For #465 the issue was that the conserved variables were not initialised before calling derivs. This was working in previous code versions because a call to prim2consall was inserted directly into the derivs routine. This was commented out because it broke the phantomNR …
=> (#543) MAXP should not be hardwired in the SETUP block

src/main/evolve.F90, src/main/initial.F90, src/main/ptmass.F90, src/main/substepping.F90, src/main/utils_dumpfiles.f90, src/setup/setup_cluster.f90, src/tests/test_ptmass.f90
Type of PR: 
Bug fix 
Description:
Crash in the header allocation while writing a small dump in the middle of the simulation. Seems to come from a bad indexing during initialization of the array `fxyz_ptmass_sinksink` in `ptmass_create`
See #547 for more details....
Testing:
=> Fix the corruption issue while creating sink dynamically

.github/workflows/build.yml, .github/workflows/krome.yml, .github/workflows/mcfost.yml, .github/workflows/test.yml
Type of PR: 
Bug fix
Description:
Update the GitHub actions to use fortran-lang/setup-fortran@v1 to install intel fortran compiler, instead of doing it manually. This is intended to fix problems with omp_lib not being correctly put in path from changes to ifort installation procedure
Testing:
Will be tested during actions on pull request
=> (github) workflow actions use fortran-lang/setup-fortran@v1

src/main/energies.F90, src/setup/setup_grtde.f90, src/utils/analysis_energies.f90, src/utils/phantomanalysis.f90
Type of PR: 
other
Description:
Attempt to address #457, add book-keeping of energy removed from the simulation due to accretion
Testing:
Low-resolution simulations of polytropes plunging into central potential with fixed accretion radius, e.g. using SETUP=grtde with both Newtonian gravity and GR. We now attempt to keep track all of the energy of the accreted particles, including the deleted potential, kinetic, thermal and magnetic energies. Previously the accreted energy in the .ev file was just GM/r, so only included the potential energy. Some caveats:
- the accounting seems to work if particles are accreted radially or as cold streams
- keeping track of Epotacc assumes that the object doing the accretion does not move (i.e. the potential is fixed in space and time). Since accreted …
=> Track accretion energy

build/Makefile_setups, src/main/inject_keplerian.f90
Type of PR: new physics
Description:
New module to inject particles at a given radius in a disc with Keplerian velocity. Implemented in "isosgdisc" and "dustyisosgdisc" setups
Testing:
We verified that the number of particles that we add per unit time matches the expected injection rate
=> New module to inject particles at a given radius in a disc with Keplerian velocity

AUTHORS, src/main/dens.F90, src/main/inject_keplerian.f90, src/setup/set_orbit.f90, src/setup/setup_grtde.f90, src/utils/analysis_disc_stresses.f90, src/utils/analysis_energies.f90, src/utils/phantomanalysis.f90
Type of PR: 
Bug fix, fixes #517 
Description:
See #517, increase maximum number of density iterations
Testing:
Tested on dump and .in in #517
=> increase maxdensits to converge on density even with bad guess for h after splitting

src/setup/setup_binary.f90
One-line fix for setting up a binary orbit in the co-rotating frame. Previously, `iexternalforce` was set to 0 prior to relaxation procedures, but this also meant that the subsequent call to `set_orbit` did not recognise that the orbit should be set in the co-rotating frame.
=> Fix bug with co-rotating frame not set correctly

build/Makefile_setups, src/setup/setup_grdisc.F90
Type of PR: 
modification to existing code 
Description:
Turned GR off for grdisc setup so that star in orbit could be added. Edited for 'dist_unit not found' error in the grdisc_setup
Testing:
Compiled without error
=> Corrected dist_unit not found error for grdisc setup w/o GR.

.gitignore, docs/developer-guide/datafiles.rst, scripts/test_analysis_ce.sh, src/main/datafiles.f90, src/main/utils_datafiles.f90
Type of PR: 
Bug fix
Description:
Fixes #580, this should fix failures occurring in all pull requests due to failures to download files from my webpage
Testing:
make SETUP=test phantomtest && ./bin/phantomtest eos
Did you update relevant documentation in the docs directory? yes
=> (#580) fix failing github actions tests by moving data files to Zenodo

build/Makefile, src/main/initial.F90, src/main/metric_et.f90, src/main/metric_et_utils.f90, src/utils/einsteintk_utils.f90, src/utils/tabulate_metric.f90
Type of PR: 
other
Description:
(gr) can use tabulated metric independently of einstein toolkit
Testing:
```
~/phantom/scripts/writemake.sh gr_testparticles > Makefile
make tabulate_metric
./tabulate_metric
make METRIC=et
make METRIC=et setup
./phantomsetup grtest
./phantom grtest.in
```
=> (gr) can use tabulated metric independently of einstein toolkit

src/main/cooling_solver.f90
Update to exact integration scheme (EIS) for radiative cooling, specifically eq. A7 in Townsend09
Type of PR:
modification to existing code, bug fix
Description:
One-sentence summary -- The index 'k' in Eq. A7 is not necessarily the same index 'k' in Eq. A5, so this pull request determines the new 'k' for A7, thereby correcting the implementation of exact cooling.
More details -- I believe that EIS was implemented in Phantom based on an EIS subroutine I had passed along years ago from our separate code.  There was an issue with the implementation that I passed along, which subsequently made its way into the Phantom implementation.  This pull request fixes that issue.
Using Townsend09 as the reference source, Eqs. A5 and A7 both use the index 'k' to refer to specific segments of the …
=> update to exact integration scheme for radiative cooling

src/main/substepping.F90
fix potentially and inadvertently shutting off accretion of gas particles onto sinks for ntypes=1
Type of PR: 
Bug fix
Description:
One-sentence summary: Removed the "iphase" call in an itype variable definition so the potential for the first particle's phase to go negative doesn't inadvertently cease the accretion of all gas particles onto all sinks.
In the subroutine kick of substepping.F90, itype is passed to the subroutine ptmass_accrete in ptmass.F90 as itypei.  ptmass_accrete then performs `is_accretable(itypei)` (line 854) as one of its accretion checks.  With the former definition of `itype = iphase(igas)`, the result of itype can either be itype=1 if particle 1 (=igas) is active (which is fine) or itype=-1 if particle 1 is inactive (which is not fine).  Passing -1 to itypei in …
=> fix inadvertently shutting off gas accretion onto sinks

src/main/substepping.F90
Type of PR: 
Bug fix
Description:
As noted in #588. There was an issue on the type of particle sent to `ptmass_accrete` when `ntypes<=1`. Only particles on the same `iphase` value  of the first particle in arrays were able to accrete. I proposed a patch 1 month ago to allow only active particles to enter in accretion loop which revealed to be a mistake. Inactive particles are meant to be awakened in the accretion loop if close enough to a sink particle. Then this feature is broken if only active particles are sent in this loop. 
The solution proposed in #588 is then the right one. 
Testing:
One line fix to reverse a mistake... No testing needed
=> (substepping) reverse 0e0cc6d patch on the particle type sent to ptmass_accrete

src/setup/setup_binary.f90
The condition to be checked should be whether `iextern_prev==iext_corotate`, not whether `iexternalforce==iextcorotate`, since `iexternalforce` was set to zero during `set_stars`
=> Small fix to binary setup

src/setup/set_star.f90, src/setup/set_star_utils.f90
Type of PR: 
Bug fix (found by @msha0023)
Description:
When setting up two gas-particle stars in a binary using `SETUP=binary` with `relax_star`, the second star is not relaxed because of an error raised by `checksetup` called in `relax_star:
```
rstar =    1.0000000000000000       mstar =   0.99935806369259794       tdyn =    1.1110774122591152     
n(via iphase)=         100           0           0         100           0           0           0           0
npartoftype  =         200           0           0           0           0           0           0           0
ERROR: sum of types in iphase is not equal to npartoftype
ERROR! relax_star: cannot relax star because particle setup contains errors
```
The cause of this is that the `npartoftype` array was not updated when particles from …
=> (set-binary) update npartoftype array when particle types are set according to a specific star in a binary

src/main/eos.f90, src/setup/setup_disc.f90
Type of PR: 
Bug fix 
Description:
Putting emission source to the primary in circumbinary disc simulation. However, isink was overriten to 0 because for circumbinary disc ieos=3.
Testing:
Running phantom on *.in file succeded.
=> set isink=1for ieos=6 in case where isink was not set

src/main/evolve.F90, src/main/initial.F90, src/main/ptmass.F90, src/main/substepping.F90, src/tests/test_ptmass.f90
Type of PR: 
modification to existing code 
Description:
A little refactor of  substep and get_force routines. The addition of subgroup routines within these ones made the whole thing too big  and unclear...
Testing:
Same tests as before... Nothing was changed in the calculation.
Did you run the bots?  no
Did you update relevant documentation in the docs directory?  no
=> Reorganize substep for clarity

src/setup/readwrite_mesa.f90
Type of PR: 
Bug fix 
Description:
In the previous PR #605, the error criterion was a bit too strong for some MESA files.
I loosened the error criterion to just require pressure and density.
Testing:
Tested star setup behaves as intended for a default MESA output file.
=> Small fix to readwrite mesa

src/main/inject_windtunnel.f90, src/setup/setup_windtunnel.f90
Type of PR: 
Description:
This p-r fixes the wind tunnel injection and setup options so that they are independent of the desire to add a "star" to the simulation.
- add add_star flag to the .setup file instead of a windonly flag in the injection module
- use the hold_star flag in the inject options to decide whether to adjust velocities inside the star. If this option is off, we do not ask for Mstar or Rstar in the injection options
- ask for Mach number rather than pressure in the injection parameters, as much simpler to understand (and dimensionless). 
- default parameters are set to give the same pres_inf as was previously hardwired (i.e. Mach 13.86)
- take particle mass directly as the input parameter for the mass resolution if no star is added to the …
=> fix windtunnel injection so it works for arbitrary wind parameters

src/main/ionization.f90, src/utils/analysis_common_envelope.f90
Type of PR:
Bug fix
Description:
phantom analysis CE recombination energy vs time not working
Testing:
=> Fix phantom analysis CE recombination energy vs time not working

src/main/cons2prim.f90, src/main/eos.f90, src/main/eos_tillotson.f90, src/main/force.F90, src/main/physcon.f90, src/main/units.f90, src/setup/relax_star.f90, src/setup/set_star.f90, src/setup/set_star_utils.f90, src/setup/setup_solarsystem.f90
Type of PR: 
Bug fix / new physics
Description:
- relax_star routine now works when setting up uniform density solar system bodies
- can specify density instead of total mass when setting up stars/bodies by giving appropriate units (e.g. "2 g/cc"). Currently there is an issue parsing units with ^ in the string, so currently must use "g/cc" rather than "g/cm^3" as the density unit.
- also silenced warnings about u < 0 when using Tillotson eos
- issue with initial value of u being hard wired for Tillotson eos fixed
Testing:
Successfully relax uniform density body with ieos=23 via SETUP=star
=> Relax asteroids

src/main/checksetup.f90, src/main/dust.f90
make drag_implicit option visible  in the .in file; give error if IND_TIMESTEPS=yes
Type of PR: 
other
Description:
The option for the Loren-Bate implicit dust scheme was hidden in the code, it is now visible to the user and makes clear that it can only be used if ind_timesteps=no
Testing:
check that code runs (dustydisc) with IND_TIMESTEPS=no, and gives error if IND_TIMESTEPS=yes
=> (dust) make drag_implicit option visible 

src/main/initial.F90
Type of PR: 
Bug fix 
Description:
Forgot to initialise `iphase` to `isink` on sink range during `startrun` routine. As `iphase` is not written in dump if there is only one type, the initialisation in `init_part` is not sufficient. This bug does not change results in tests as they're using `init_part`.
Testing:
Nothing changed
Did you run the bots?no
=> Hotfix for sink in tree new method

src/main/utils_infiles.f90, src/setup/set_solarsystem.f90, src/setup/setup_solarsystem.f90, src/utils/utils_ephemeris.f90
Type of PR: 
Bug fix
Description:
- Using au as the units for small bodies in the solar system causes problems with finite precision (round off error). This is now changed to km as the length unit
- fix issue with datetime string for epoch being converted automatically
- better error handling if ephemeris files cannot be downloaded
Testing:
- checked that orbits of the 9 planets+moon still works in these units
=> (solarsystem) use km as length unit for solar system setup

src/setup/set_star_utils.f90
Bug fix: Should not interpolate particle mean molecular weight in `set_star_composition` when `eos_outputs_mu(ieos)=.true.`, since mu should be set when calling equationofstate in `set_star_thermalenergy`. This makes sense since the mean molecular weight is in general not a composition variable, but a thermodynamic variable.
=> (star) fix logic with star setup using eos that outputs mu

src/main/initial.F90, src/main/ptmass.F90, src/main/subgroup.f90, src/main/substepping.F90
Type of PR: 
Bug fix 
Description:
A reduction on bin_info was performed in the `get_force` routine to track perturbations of the gas on subgroups. During the calculation, the code needed to look up some variables stored in another column of the same array which was initialized at zero due to the reduction clause... This is easily fixed using a temporary array to do the reduction. 
Testing:
=> Issue with omp reduction

.mailmap, AUTHORS, build/Makefile_setups, docs/examples/star.rst, src/main/apr.f90, src/main/apr_region.f90, src/main/dust.f90, src/main/externalforces.f90, src/main/externalforces_gr.f90, src/main/force.F90, src/main/kdtree.F90, src/main/ptmass.F90, src/main/subgroup.f90, src/main/utils_raytracer.f90, src/setup/set_star.f90, src/setup/set_star_utils.f90, src/setup/setup_grtde.f90, src/setup/setup_star.f90, src/tests/test_gravity.f90, src/utils/utils_raytracer_all.f90
Type of PR: 
Modification of existing code
Description:
- modified SETUP=tde to use setup_grtde.f90 instead of setup_star.f90
- modification necessary to make setup_grtde work for the SETUP=tde
- separate definition black hole mass from units settings
- added option for accretion radius in the .setup file
- consistent way to set up central mass and black hole spin for gr/non gr code
Testing:
```
~/phantom/scripts/writemake.sh tde > Makefile
make; make setup
./phantomsetup tde
```
Did you update relevant documentation in the docs directory? yes
=> tde setup for white dwarfs with fake GR

src/main/checksetup.f90, src/main/config.F90, src/main/kdtree.F90, src/main/part.F90, src/main/substepping.F90, src/tests/test_ptmass.f90
Type of PR: 
Bug fix
Description:
Fix for #635 reported by Vasu Prasad. The underlying issue was breaking of backwards compatibility with previous runs using dust particles because the dust particle type had been shuffled by +1 to make room for the isink particle type.
A better solution is to make the isink type needed to identify sink particles in the tree equal to 0. This works because it is also the "unknown" particle type, does not correspond to an entry in the massoftype array, and does not need a sign when referenced as iphase because sink particles cannot be active/inactive.
Testing:
Using dump file standard_run_00122 supplied by Vasu. This file has 10^6 gas particles (type 1) and 10^5 dust particles of type 7. The seg fault occurred because the type 7 particles read from the dump …
=> (#635) fix seg fault caused by shuffling of particle types by 1

docs/physics/sink-properties.rst, src/main/config.F90, src/main/evolve.F90, src/main/part.F90, src/main/ptmass.F90, src/main/readwrite_dumps_common.f90, src/main/readwrite_dumps_fortran.f90, src/main/step_leapfrog.F90, src/main/substepping.F90, src/tests/test_gr.f90, src/tests/test_ptmass.f90
Type of PR: 
Cleaning
Description:
There is no need to separate `sf_ptmass` and `xyzmh_ptmass`. Merging both simplifies the read and write of dumps and lightens main routine interfaces.
Testing:
All ptmass tests with `icreate_sinks == 2` pass
=> Merge sf_ptmass array in xyzmh_ptmass

src/setup/setup_disc.f90
Type of PR: 
Bug fix
Description:
fixed bug in setup_disc.f90 (use_sigma_file to sigma_file)
Testing:
Run circumbinary, circumprimary and circumsecondary discs setups
=> (setup_disc.f90) Renamed use_sigma_file to sigma_file.

src/main/utils_filenames.f90
Type of PR: 
Bug fix
Description:
increase file number digits when the number overflows so it does not give **
Testing:
ev/log file number increase digit correctly to 100 when exceed 99
also tested with dumps, when dump exceed 99999 the digit increases correctly to 100000
=> ev file goes beyond 99

src/main/ptmass.F90, src/main/ptmass_heating.f90
Type of PR: 
Bug fix
Description:
Fixes a bug in `ptmass_heating.f90::47` when there's a mix of sink particles with and without sink heating.
Because the code skips calculating the no-sink-heating sink particle's `massenc`, so when there's gas particles near that sink, it thinks `xyzmh_ptmass(imassenc,i)==0` for that sink particle and encounters a division by zero error.
Here is a quick fix for this.
Testing:
`make test` passes.
Previously crashing simulations stopped crashing.
=> fix ptmass_heating division by zero error crashes

docs/user-guide/config.rst, docs/user-guide/data-curation.rst
Description:
Adding authorship guidelines to the docs from the 2025 European workshop.
=> Adding authorship guidelines

src/utils/analysis_common_envelope.f90
Description:
There seems to be several bugs in the radius calculations in the *star stabilization suite* in `phantomanalysis`.
For example, the `ipartrad` actually calculates the particle density radius instead of particle radius,
and the `ipdensrad`, instead of calculating the particle density radius, doesn't seem to calculate anything physical (because `iorder_a` is not actually sorting 'particles within surface by radius', since `xyzh` is not a sorted array; it is just sorting the first `npart_a` number of particles, which are not necessarily all within the surface);
also there seems to be a missing factor of 2 for the particle 2h radius calculations.
This results in some very confusing outputs, such as the calculated particle radius is smaller than the particle density radius, which …
=> Fix analysis common envelope star stability radius definitions

src/main/force.F90, src/main/part.F90
Description:
I discovered a wrong behaviour of the sinktree method while debugging #699.  If we had a cache miss, the fallback was on the wrong array (if the neighbour was a sink). Difficult to detect that with tests, as the number of parts is set to 1000 (same as the cache size) in most cases. 
Also removed the ptmass killing in 'accrete_particles_outside_sphere' as it had unexpected behaviour with the subgrouping module...
Did you add comments such that the purpose of the code is understandable? no
Is there a unit test that could be added for this feature/bug? yes
If so, please describe what a unit test might check:
We should increase the number of parts in …
=> (Sinktree) Wrong fallback behaviour when sink are not in cache

src/main/ptmass.F90, src/main/utils_dumpfiles.f90, src/tests/test_ptmass.f90
Description:
There were mistakes made in `ptmass_merge_release` that have been fixed. I had corruption in the ptmass array in my sims due to an interference between the subgroup routines and `update_ptmass`, which is fixed now. This routine has also been parallelised. I spotted a typo in `read_array_int4arr`. Nothing dangerous, as it is not used in the code. 
Finally, I refined the conditional sink merging for `icreate_sinks==2`. I added a square root to `Epot` in this condition. Looks like it was forgotten for a while... (I corrected the tests accordingly)
Testing:
checked if ptmass tests were all green.
Did you add comments such that the purpose of the code is …
=> fixes on ptmass merge routines

src/main/ptmass.F90, src/main/substepping.F90, src/tests/test_ptmass.f90
Description:
The accretion routine has remained unchanged since the public repository was created. It is never a major bottleneck when the number of point masses is low. In my case, this part of the code could easily eat 40 to 60 % of the wall time when this number starts to rise up to a few thousand. I've changed the checks logic (however, the physical tests are identical) in this routine to avoid duplicate tests for nothing (especially in the most bound part tests). It also allowed me to refactor the code. `ptmass_accrete` and `kick` have been split in half, separating checks from accumulation in the first one and kicking and accreting in the latter.
I also simplified the last calls in a substep to be agnostic of one integrator or method to another. 
The perf gain is negligible for now, …
=> Refactor accretion checks

.github/workflows/build.yml, .github/workflows/growth.yml, .github/workflows/krome.yml, .github/workflows/mcfost.yml, .github/workflows/mpi.yml, .github/workflows/on_pr.yml, .github/workflows/on_push.yml, .github/workflows/test.yml, src/main/mpi_derivs.F90
Description:
This PR split the ci workflow into 1 file = 1 event and call the subsequent jobs using workflow calls to avoid duplication.
This allows the usage of GitHub job concurrency on PR to auto cancel old jobs if a new commit is pushed to the PR in the meantime
Testing:
Did you add comments such that the purpose of the code is understandable? no
Is there a unit test that could be added for this feature/bug? no
=> [CI] split ci by events and add concurrency on PR

src/setup/stretchmap.f90
Description:
This PR fixes the sporadic failure in the test suite identified in #689. The code crashed due to a density set to `0.`  in `yinterp`, which was used in a division later in `strechmap.f90`. Sporadically, the `xtable` array had random values inside `yinterp`.   `xtable` was passed to `yinterp`  as `xtable(1:nt)`. I have read online that passing the array as a slice could result in a copy instead of passing a pointer when using no optimisation. `-O0` aocc compilation option is not fully tested yet and could hide a bug while doing this copy... This issue disappears with any other optimisation option, which suggests that it may be a compiler bug. I have tried to reproduce the issue in a simple snippet with no results... Passing `xtable` without the slice (not necessary in this …
=> fix aocc build failure #689

src/main/utils_orbits.f90, src/setup/set_orbit.f90, src/setup/setup_binary.f90, src/setup/setup_disc.f90, src/setup/setup_grdisc.f90, src/setup/setup_grtde.f90, src/tests/test_orbits.f90
This p-r implements functionality to be able to specify the observed separation and velocity of two stars in a flyby encounter, and run the orbit so that the stars finish at exactly that separation and velocity difference
Description:
- implemented new option in set_orbits
- reworked setup_disc to use set_orbits instead of directly calling set_binary
- fix issues in some of the orbits helper routines for getting true anomaly from separation
Testing:
running SETUP=disc for a flyby
Did you add comments such that the purpose of the code is understandable? yes
Is there a unit test that could be added for this feature/bug? yes
If so, please describe what a unit test …
=> Flyby reconstructor^TM
